/**
 * Template page - directly imports from theme
 * Template: app/dashboard/analytics/loading.tsx
 * Generated by: scripts/build-registry.mjs
 */
import TemplateComponent from '@/contents/themes/barbercrm/templates/dashboard/analytics/loading'

// Direct export of the theme template (no fallback)
export default TemplateComponent
