export const dynamic = 'force-dynamic'

/**
 * Template page - directly imports from theme
 * Template: app/dashboard/analytics/page.tsx
 * Generated by: scripts/build-registry.mjs
 */
import TemplateComponent from '@/contents/themes/barbercrm/templates/dashboard/analytics/page'

// Direct export of the theme template (no fallback)
export default TemplateComponent
