import type { EntityField } from '@nextsparkjs/core/lib/entities/types'

export const clientFields: EntityField[] = [
  {
    name: 'name',
    type: 'text',
    required: true,
    display: {
      label: 'Full Name',
      description: 'Client full name',
      placeholder: 'Enter client name...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 1,
      columnWidth: 8,
    },
    api: { readOnly: false, searchable: true, sortable: true },
  },
  {
    name: 'phone',
    type: 'text',
    required: false,
    display: {
      label: 'Phone',
      description: 'Client phone number',
      placeholder: '+1 555 000 0000',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 2,
      columnWidth: 4,
    },
    api: { readOnly: false, searchable: true, sortable: false },
  },
  {
    name: 'email',
    type: 'text',
    required: false,
    display: {
      label: 'Email',
      description: 'Client email address',
      placeholder: 'client@email.com',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 3,
      columnWidth: 6,
    },
    api: { readOnly: false, searchable: true, sortable: false },
  },
  {
    name: 'preferredService',
    type: 'text',
    required: false,
    display: {
      label: 'Preferred Service',
      description: 'Client\'s usual service',
      placeholder: 'e.g. Fade + Beard',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 4,
      columnWidth: 6,
    },
    api: { readOnly: false, searchable: true, sortable: false },
  },
  {
    name: 'visitFrequency',
    type: 'number',
    required: false,
    display: {
      label: 'Visit Frequency (days)',
      description: 'How often the client visits (in days)',
      placeholder: '21',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 5,
      columnWidth: 4,
    },
    api: { readOnly: false, searchable: false, sortable: true },
  },
  {
    name: 'notes',
    type: 'textarea',
    required: false,
    display: {
      label: 'Notes',
      description: 'Internal notes about the client',
      placeholder: 'Add notes...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 6,
      columnWidth: 12,
    },
    api: { readOnly: false, searchable: false, sortable: false },
  },
]
