import type { EntityField } from '@nextsparkjs/core/lib/entities/types'

export const serviceFields: EntityField[] = [
  {
    name: 'name',
    type: 'text',
    required: true,
    display: {
      label: 'Service Name',
      description: 'Name of the service',
      placeholder: 'e.g. Fade Haircut',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 1,
      columnWidth: 8,
    },
    api: { readOnly: false, searchable: true, sortable: true },
  },
  {
    name: 'category',
    type: 'select',
    required: false,
    defaultValue: 'haircut',
    options: [
      { value: 'haircut', label: 'Haircut' },
      { value: 'beard', label: 'Beard' },
      { value: 'color', label: 'Color' },
      { value: 'treatment', label: 'Treatment' },
      { value: 'other', label: 'Other' },
    ],
    display: {
      label: 'Category',
      description: 'Service category',
      placeholder: 'Select category...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 2,
      columnWidth: 4,
    },
    api: { readOnly: false, searchable: false, sortable: true },
  },
  {
    name: 'price',
    type: 'number',
    required: true,
    display: {
      label: 'Price',
      description: 'Service price',
      placeholder: '0.00',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 3,
      columnWidth: 4,
    },
    api: { readOnly: false, searchable: false, sortable: true },
  },
  {
    name: 'duration',
    type: 'number',
    required: true,
    display: {
      label: 'Duration (min)',
      description: 'Service duration in minutes',
      placeholder: '30',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 4,
      columnWidth: 4,
    },
    api: { readOnly: false, searchable: false, sortable: true },
  },
  {
    name: 'active',
    type: 'boolean',
    required: false,
    defaultValue: true,
    display: {
      label: 'Active',
      description: 'Whether the service is currently offered',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 5,
      columnWidth: 4,
    },
    api: { readOnly: false, searchable: false, sortable: false },
  },
  {
    name: 'description',
    type: 'textarea',
    required: false,
    display: {
      label: 'Description',
      description: 'Service description',
      placeholder: 'Describe the service...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 6,
      columnWidth: 12,
    },
    api: { readOnly: false, searchable: false, sortable: false },
  },
]
