/**
 * Auto-generated Block Registry
 *
 * Generated at: 2026-05-31T16:00:45.253Z
 * Blocks discovered: 1
 * Categories: hero
 *
 * This registry provides build-time access to all block definitions.
 * Use this for admin UI (block picker, form generation) and API endpoints.
 *
 * DO NOT EDIT - This file is auto-generated by scripts/build-registry.mjs
 */

import React from 'react'
import type { BlockConfig, BlockCategory } from '@nextsparkjs/core/types'

import { fieldDefinitions as hero_fields } from '@/contents/themes/barbercrm/blocks/hero/fields'

// Direct component imports for SSR — zero CLS, synchronous hydration
import { default as hero_component } from '@/contents/themes/barbercrm/blocks/hero/component'

export const BLOCK_REGISTRY: Record<string, BlockConfig> = {
  'hero': {
    slug: 'hero',
    name: 'Hero Section',
    description: 'Full-width hero section with title, subtitle, CTA button, and background image',
    category: 'hero' as BlockCategory,
    icon: 'Rocket',
    componentPath: '@/contents/themes/barbercrm/blocks/hero/component',
    schemaPath: '@/contents/themes/barbercrm/blocks/hero/schema',
    fieldsPath: '@/contents/themes/barbercrm/blocks/hero/fields',
    thumbnail: undefined,
    fieldDefinitions: hero_fields,
    examples: [],
    scope: ['pages', 'posts'],
    allowInPatterns: undefined,
    isCore: false,
    source: 'theme' as const,
    sourceId: 'barbercrm'
  }
}

export const BLOCK_CATEGORIES: BlockCategory[] = ['hero']

/**
 * Lazy-loaded block components for client-side rendering (admin UI, block picker).
 * Each component is wrapped with React.lazy for code-splitting.
 */
export const BLOCK_COMPONENTS: Record<string, React.LazyExoticComponent<React.ComponentType<any>>> = {
  'hero': React.lazy(() => import('@/contents/themes/barbercrm/blocks/hero/component').then(mod => ({ default: Object.values(mod)[0] as React.ComponentType<any> })))
}

/**
 * Direct-imported block components for SSR rendering.
 * Static imports ensure synchronous hydration — zero CLS.
 * HTML is fully visible without client JS (SEO-safe, no-JS compatible).
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const BLOCK_COMPONENTS_SSR: Record<string, React.ComponentType<any>> = {
  'hero': hero_component
}

/**
 * Block registry metadata
 */
export const BLOCK_METADATA = {
  totalBlocks: 1,
  categories: ['hero'],
  blocksByCategory: {
    'hero': 1
  },
  generatedAt: '2026-05-31T16:00:45.253Z',
  blocks: ['hero']
}
