/**
 * Auto-generated Email Registry
 *
 * Generated at: 2026-05-31T16:00:45.253Z
 * Templates discovered: 1
 * Sources: verify-email(theme)
 *
 * DO NOT EDIT - This file is auto-generated by scripts/build/registry.mjs.
 * Override behaviour: drop a file at `themes/<active-theme>/emails/<slug>.ts`
 * and rebuild — the theme version wins over the core default at the same slug,
 * and entirely new slugs from a theme are additive.
 *
 * Type safety: this file emits a literal object with `as const` so TypeScript
 * infers per-slug data types from each imported function's signature.
 * Do NOT add a `Record<string, …>` annotation — that would erase the per-slug
 * inference and consumer-defined slugs would lose type safety.
 */

import verifyEmail_theme from '@/contents/themes/barbercrm/emails/verify-email'

export const EMAIL_REGISTRY = {
  'verify-email': verifyEmail_theme,
} as const

export type EmailSlug = keyof typeof EMAIL_REGISTRY

export const EMAIL_REGISTRY_METADATA = {
  'verify-email': { source: 'theme' as const, overridden: true },
} as const

export const EMAIL_REGISTRY_INFO = {
  totalTemplates: 1,
  generatedAt: '2026-05-31T16:00:45.253Z',
  slugs: ['verify-email'] as const,
} as const
