/**
 * Auto-generated Entity Registry
 *
 * Generated at: 2026-05-31T11:38:05.451Z
 * Entities discovered: 9
 *
 * DO NOT EDIT - This file is auto-generated by scripts/build-registry.mjs
 */

import { patternsEntityConfig } from '@nextsparkjs/core/entities/patterns/patterns.config'
import { appointmentEntityConfig } from '@/contents/themes/barbercrm/entities/appointments/appointments.config'
import { barberEntityConfig } from '@/contents/themes/barbercrm/entities/barbers/barbers.config'
import { clientEntityConfig } from '@/contents/themes/barbercrm/entities/clients/clients.config'
import { pagesEntityConfig } from '@/contents/themes/barbercrm/entities/pages/pages.config'
import { postsEntityConfig } from '@/contents/themes/barbercrm/entities/posts/posts.config'
import { productEntityConfig } from '@/contents/themes/barbercrm/entities/products/products.config'
import { serviceEntityConfig } from '@/contents/themes/barbercrm/entities/services/services.config'
import { taskEntityConfig } from '@/contents/themes/barbercrm/entities/tasks/tasks.config'
import type { EntityConfig, ChildEntityDefinition } from '@nextsparkjs/core/lib/entities/types'

export interface EntityPluginContext {
  pluginName: string
}

export interface EntityThemeContext {
  themeName: string
}

export interface EntityRegistryEntry {
  name: string
  config: EntityConfig | ChildEntityDefinition
  tableName?: string
  relativePath: string
  depth: number
  parent: string | null
  children: string[]
  hasComponents: boolean
  hasHooks: boolean
  hasMigrations: boolean
  hasMessages: boolean
  hasAssets: boolean
  messagesPath: string
  pluginContext: EntityPluginContext | null
  themeContext: EntityThemeContext | null
  isCore?: boolean
  source?: 'core' | 'theme' | 'plugin'
}

export const ENTITY_REGISTRY = {
  'patterns': {
    name: 'patterns',
    config: patternsEntityConfig,
    tableName: patternsEntityConfig.slug || 'patterns',
    relativePath: 'patterns',
    depth: 0,
    parent: null,
    children: [],
    hasComponents: false,
    hasHooks: false,
    hasMigrations: false,
    hasMessages: true,
    hasAssets: false,
    messagesPath: '@nextsparkjs/core/entities/patterns/messages',
    pluginContext: null,
    themeContext: null,
    isCore: true,
    source: 'core' as const
  },
  'appointments': {
    name: 'appointments',
    config: appointmentEntityConfig,
    tableName: appointmentEntityConfig.slug || 'appointments',
    relativePath: 'appointments',
    depth: 0,
    parent: null,
    children: [],
    hasComponents: false,
    hasHooks: false,
    hasMigrations: true,
    hasMessages: true,
    hasAssets: false,
    messagesPath: '@/contents/themes/barbercrm/entities/appointments/messages',
    pluginContext: null,
    themeContext: { themeName: 'barbercrm' },
    isCore: false,
    source: 'theme' as const
  },
  'barbers': {
    name: 'barbers',
    config: barberEntityConfig,
    tableName: barberEntityConfig.slug || 'barbers',
    relativePath: 'barbers',
    depth: 0,
    parent: null,
    children: [],
    hasComponents: false,
    hasHooks: false,
    hasMigrations: true,
    hasMessages: true,
    hasAssets: false,
    messagesPath: '@/contents/themes/barbercrm/entities/barbers/messages',
    pluginContext: null,
    themeContext: { themeName: 'barbercrm' },
    isCore: false,
    source: 'theme' as const
  },
  'clients': {
    name: 'clients',
    config: clientEntityConfig,
    tableName: clientEntityConfig.slug || 'clients',
    relativePath: 'clients',
    depth: 0,
    parent: null,
    children: [],
    hasComponents: false,
    hasHooks: false,
    hasMigrations: true,
    hasMessages: true,
    hasAssets: false,
    messagesPath: '@/contents/themes/barbercrm/entities/clients/messages',
    pluginContext: null,
    themeContext: { themeName: 'barbercrm' },
    isCore: false,
    source: 'theme' as const
  },
  'pages': {
    name: 'pages',
    config: pagesEntityConfig,
    tableName: pagesEntityConfig.slug || 'pages',
    relativePath: 'pages',
    depth: 0,
    parent: null,
    children: [],
    hasComponents: false,
    hasHooks: false,
    hasMigrations: true,
    hasMessages: true,
    hasAssets: false,
    messagesPath: '@/contents/themes/barbercrm/entities/pages/messages',
    pluginContext: null,
    themeContext: { themeName: 'barbercrm' },
    isCore: false,
    source: 'theme' as const
  },
  'posts': {
    name: 'posts',
    config: postsEntityConfig,
    tableName: postsEntityConfig.slug || 'posts',
    relativePath: 'posts',
    depth: 0,
    parent: null,
    children: [],
    hasComponents: true,
    hasHooks: false,
    hasMigrations: true,
    hasMessages: true,
    hasAssets: false,
    messagesPath: '@/contents/themes/barbercrm/entities/posts/messages',
    pluginContext: null,
    themeContext: { themeName: 'barbercrm' },
    isCore: false,
    source: 'theme' as const
  },
  'products': {
    name: 'products',
    config: productEntityConfig,
    tableName: productEntityConfig.slug || 'products',
    relativePath: 'products',
    depth: 0,
    parent: null,
    children: [],
    hasComponents: false,
    hasHooks: false,
    hasMigrations: true,
    hasMessages: true,
    hasAssets: false,
    messagesPath: '@/contents/themes/barbercrm/entities/products/messages',
    pluginContext: null,
    themeContext: { themeName: 'barbercrm' },
    isCore: false,
    source: 'theme' as const
  },
  'services': {
    name: 'services',
    config: serviceEntityConfig,
    tableName: serviceEntityConfig.slug || 'services',
    relativePath: 'services',
    depth: 0,
    parent: null,
    children: [],
    hasComponents: false,
    hasHooks: false,
    hasMigrations: true,
    hasMessages: true,
    hasAssets: false,
    messagesPath: '@/contents/themes/barbercrm/entities/services/messages',
    pluginContext: null,
    themeContext: { themeName: 'barbercrm' },
    isCore: false,
    source: 'theme' as const
  },
  'tasks': {
    name: 'tasks',
    config: taskEntityConfig,
    tableName: taskEntityConfig.slug || 'tasks',
    relativePath: 'tasks',
    depth: 0,
    parent: null,
    children: [],
    hasComponents: false,
    hasHooks: false,
    hasMigrations: true,
    hasMessages: true,
    hasAssets: false,
    messagesPath: '@/contents/themes/barbercrm/entities/tasks/messages',
    pluginContext: null,
    themeContext: { themeName: 'barbercrm' },
    isCore: false,
    source: 'theme' as const
  }
}

export type EntityName = keyof typeof ENTITY_REGISTRY

/**
 * Entity registry metadata
 */
export const ENTITY_METADATA = {
  totalEntities: 9,
  pluginEntities: 0,
  themeEntities: 8,
  entitiesWithComponents: 1,
  entitiesWithHooks: 0,
  entitiesWithMigrations: 8,
  entitiesWithMessages: 9,
  entitiesWithAssets: 0,
  maxDepth: 0,
  generatedAt: '2026-05-31T11:38:05.451Z',
  entities: ['patterns', 'appointments', 'barbers', 'clients', 'pages', 'posts', 'products', 'services', 'tasks']
}

// Query functions have been moved to: @nextsparkjs/core/lib/entities/queries
// Import from there instead:
// import { getEntity, getRegisteredEntities, ... } from '@nextsparkjs/core/lib/entities/queries'
