'use client'

/**
 * Client-Safe Entity Registry
 *
 * Generated at: 2026-05-31T11:38:05.452Z
 * Entities discovered: 9
 *
 * This is the client-safe version of the entity registry.
 * Contains only configuration data safe for client components.
 * NO server-side imports or server-only dependencies.
 *
 * DO NOT EDIT - This file is auto-generated by scripts/build-registry.mjs
 */

import { patternsEntityConfig } from '@nextsparkjs/core/entities/patterns/patterns.config'
import { appointmentEntityConfig } from '@/contents/themes/barbercrm/entities/appointments/appointments.config'
import { barberEntityConfig } from '@/contents/themes/barbercrm/entities/barbers/barbers.config'
import { clientEntityConfig } from '@/contents/themes/barbercrm/entities/clients/clients.config'
import { pagesEntityConfig } from '@/contents/themes/barbercrm/entities/pages/pages.config'
import { postsEntityConfig } from '@/contents/themes/barbercrm/entities/posts/posts.config'
import { productEntityConfig } from '@/contents/themes/barbercrm/entities/products/products.config'
import { serviceEntityConfig } from '@/contents/themes/barbercrm/entities/services/services.config'
import { taskEntityConfig } from '@/contents/themes/barbercrm/entities/tasks/tasks.config'
import { registerEntityIcon } from '@nextsparkjs/core/lib/entities/registry.client'

// Pre-register entity icons so non-lucide icons survive server→client serialization
registerEntityIcon('patterns', patternsEntityConfig.icon)
registerEntityIcon('appointments', appointmentEntityConfig.icon)
registerEntityIcon('barbers', barberEntityConfig.icon)
registerEntityIcon('clients', clientEntityConfig.icon)
registerEntityIcon('pages', pagesEntityConfig.icon)
registerEntityIcon('posts', postsEntityConfig.icon)
registerEntityIcon('products', productEntityConfig.icon)
registerEntityIcon('services', serviceEntityConfig.icon)
registerEntityIcon('tasks', taskEntityConfig.icon)

export interface ClientEntityConfig {
  name: string
  apiPath: string
  tableName?: string
  displayName: string
  relativePath: string
  depth: number
  parent: string | null
  children: string[]
  hasComponents: boolean
  hasHooks: boolean
  hasMigrations: boolean
  hasMessages: boolean
  hasAssets: boolean
  messagesPath: string
  pluginContext: { pluginName: string } | null
  themeContext: { themeName: string } | null
  isCore: boolean
  source: 'core' | 'theme' | 'plugin'
  access?: {
    basePath?: string
  }
  features: {
    enabled: boolean
    canCreate?: boolean
    canEdit?: boolean
    canDelete?: boolean
    searchable?: boolean
    showInMenu?: boolean
  }
  builder?: {
    enabled: boolean
    sidebarFields?: string[]
    sidebarFieldsConfig?: Array<{
      name: string
      type: string
      label?: string
      placeholder?: string
      rows?: number
      relation?: { entity: string; titleField: string; userFiltered?: boolean; limit?: number; filter?: Record<string, string> }
      options?: Array<{ value: string; label: string }>
      conditionalOn?: { field: string; value: string | string[] }
    }>
    showSlug?: boolean
    public?: { basePath: string }
    seo?: boolean
  }
  taxonomies?: {
    enabled: boolean
    types: { type: string; field: string; multiple: boolean; label?: string }[]
  }
}

export interface ClientEntityRegistry {
  [key: string]: ClientEntityConfig
}

// Entity name type for type safety
export type EntityName = 'patterns' | 'appointments' | 'barbers' | 'clients' | 'pages' | 'posts' | 'products' | 'services' | 'tasks'

// Client-safe entity registry (no server-side imports)
export const ENTITY_REGISTRY: ClientEntityRegistry = {
  'patterns': {
    name: 'patterns',
    apiPath: patternsEntityConfig.slug || 'patterns',
    tableName: patternsEntityConfig.slug,
    displayName: patternsEntityConfig.names?.singular || patternsEntityConfig.slug || 'patterns',
    relativePath: 'patterns',
    depth: 0,
    parent: null,
    children: [],
    hasComponents: false,
    hasHooks: false,
    hasMigrations: false,
    hasMessages: true,
    hasAssets: false,
    messagesPath: '@nextsparkjs/core/entities/patterns/messages',
    pluginContext: null,
    themeContext: null,
    isCore: true,
    source: 'core',
    access: patternsEntityConfig.access?.basePath ? {
      basePath: patternsEntityConfig.access.basePath
    } : undefined,
    features: {
      enabled: patternsEntityConfig.enabled !== false,
      canCreate: true,
      canEdit: true,
      canDelete: true,
      searchable: true,
      showInMenu: patternsEntityConfig.ui?.dashboard?.showInMenu !== false
    },
    builder: patternsEntityConfig.builder ? {
      enabled: patternsEntityConfig.builder.enabled,
      sidebarFields: patternsEntityConfig.builder.sidebarFields,
      sidebarFieldsConfig: patternsEntityConfig.builder.sidebarFieldsConfig,
      showSlug: patternsEntityConfig.builder.showSlug,
      public: patternsEntityConfig.builder.public,
      seo: patternsEntityConfig.builder.seo
    } : undefined,
    taxonomies: patternsEntityConfig.taxonomies ? {
      enabled: patternsEntityConfig.taxonomies.enabled,
      types: patternsEntityConfig.taxonomies.types
    } : undefined
  },
  'appointments': {
    name: 'appointments',
    apiPath: appointmentEntityConfig.slug || 'appointments',
    tableName: appointmentEntityConfig.slug,
    displayName: appointmentEntityConfig.names?.singular || appointmentEntityConfig.slug || 'appointments',
    relativePath: 'appointments',
    depth: 0,
    parent: null,
    children: [],
    hasComponents: false,
    hasHooks: false,
    hasMigrations: true,
    hasMessages: true,
    hasAssets: false,
    messagesPath: '@/contents/themes/barbercrm/entities/appointments/messages',
    pluginContext: null,
    themeContext: { themeName: 'barbercrm' },
    isCore: false,
    source: 'theme',
    access: appointmentEntityConfig.access?.basePath ? {
      basePath: appointmentEntityConfig.access.basePath
    } : undefined,
    features: {
      enabled: appointmentEntityConfig.enabled !== false,
      canCreate: true,
      canEdit: true,
      canDelete: true,
      searchable: true,
      showInMenu: appointmentEntityConfig.ui?.dashboard?.showInMenu !== false
    },
    builder: appointmentEntityConfig.builder ? {
      enabled: appointmentEntityConfig.builder.enabled,
      sidebarFields: appointmentEntityConfig.builder.sidebarFields,
      sidebarFieldsConfig: appointmentEntityConfig.builder.sidebarFieldsConfig,
      showSlug: appointmentEntityConfig.builder.showSlug,
      public: appointmentEntityConfig.builder.public,
      seo: appointmentEntityConfig.builder.seo
    } : undefined,
    taxonomies: appointmentEntityConfig.taxonomies ? {
      enabled: appointmentEntityConfig.taxonomies.enabled,
      types: appointmentEntityConfig.taxonomies.types
    } : undefined
  },
  'barbers': {
    name: 'barbers',
    apiPath: barberEntityConfig.slug || 'barbers',
    tableName: barberEntityConfig.slug,
    displayName: barberEntityConfig.names?.singular || barberEntityConfig.slug || 'barbers',
    relativePath: 'barbers',
    depth: 0,
    parent: null,
    children: [],
    hasComponents: false,
    hasHooks: false,
    hasMigrations: true,
    hasMessages: true,
    hasAssets: false,
    messagesPath: '@/contents/themes/barbercrm/entities/barbers/messages',
    pluginContext: null,
    themeContext: { themeName: 'barbercrm' },
    isCore: false,
    source: 'theme',
    access: barberEntityConfig.access?.basePath ? {
      basePath: barberEntityConfig.access.basePath
    } : undefined,
    features: {
      enabled: barberEntityConfig.enabled !== false,
      canCreate: true,
      canEdit: true,
      canDelete: true,
      searchable: true,
      showInMenu: barberEntityConfig.ui?.dashboard?.showInMenu !== false
    },
    builder: barberEntityConfig.builder ? {
      enabled: barberEntityConfig.builder.enabled,
      sidebarFields: barberEntityConfig.builder.sidebarFields,
      sidebarFieldsConfig: barberEntityConfig.builder.sidebarFieldsConfig,
      showSlug: barberEntityConfig.builder.showSlug,
      public: barberEntityConfig.builder.public,
      seo: barberEntityConfig.builder.seo
    } : undefined,
    taxonomies: barberEntityConfig.taxonomies ? {
      enabled: barberEntityConfig.taxonomies.enabled,
      types: barberEntityConfig.taxonomies.types
    } : undefined
  },
  'clients': {
    name: 'clients',
    apiPath: clientEntityConfig.slug || 'clients',
    tableName: clientEntityConfig.slug,
    displayName: clientEntityConfig.names?.singular || clientEntityConfig.slug || 'clients',
    relativePath: 'clients',
    depth: 0,
    parent: null,
    children: [],
    hasComponents: false,
    hasHooks: false,
    hasMigrations: true,
    hasMessages: true,
    hasAssets: false,
    messagesPath: '@/contents/themes/barbercrm/entities/clients/messages',
    pluginContext: null,
    themeContext: { themeName: 'barbercrm' },
    isCore: false,
    source: 'theme',
    access: clientEntityConfig.access?.basePath ? {
      basePath: clientEntityConfig.access.basePath
    } : undefined,
    features: {
      enabled: clientEntityConfig.enabled !== false,
      canCreate: true,
      canEdit: true,
      canDelete: true,
      searchable: true,
      showInMenu: clientEntityConfig.ui?.dashboard?.showInMenu !== false
    },
    builder: clientEntityConfig.builder ? {
      enabled: clientEntityConfig.builder.enabled,
      sidebarFields: clientEntityConfig.builder.sidebarFields,
      sidebarFieldsConfig: clientEntityConfig.builder.sidebarFieldsConfig,
      showSlug: clientEntityConfig.builder.showSlug,
      public: clientEntityConfig.builder.public,
      seo: clientEntityConfig.builder.seo
    } : undefined,
    taxonomies: clientEntityConfig.taxonomies ? {
      enabled: clientEntityConfig.taxonomies.enabled,
      types: clientEntityConfig.taxonomies.types
    } : undefined
  },
  'pages': {
    name: 'pages',
    apiPath: pagesEntityConfig.slug || 'pages',
    tableName: pagesEntityConfig.slug,
    displayName: pagesEntityConfig.names?.singular || pagesEntityConfig.slug || 'pages',
    relativePath: 'pages',
    depth: 0,
    parent: null,
    children: [],
    hasComponents: false,
    hasHooks: false,
    hasMigrations: true,
    hasMessages: true,
    hasAssets: false,
    messagesPath: '@/contents/themes/barbercrm/entities/pages/messages',
    pluginContext: null,
    themeContext: { themeName: 'barbercrm' },
    isCore: false,
    source: 'theme',
    access: pagesEntityConfig.access?.basePath ? {
      basePath: pagesEntityConfig.access.basePath
    } : undefined,
    features: {
      enabled: pagesEntityConfig.enabled !== false,
      canCreate: true,
      canEdit: true,
      canDelete: true,
      searchable: true,
      showInMenu: pagesEntityConfig.ui?.dashboard?.showInMenu !== false
    },
    builder: pagesEntityConfig.builder ? {
      enabled: pagesEntityConfig.builder.enabled,
      sidebarFields: pagesEntityConfig.builder.sidebarFields,
      sidebarFieldsConfig: pagesEntityConfig.builder.sidebarFieldsConfig,
      showSlug: pagesEntityConfig.builder.showSlug,
      public: pagesEntityConfig.builder.public,
      seo: pagesEntityConfig.builder.seo
    } : undefined,
    taxonomies: pagesEntityConfig.taxonomies ? {
      enabled: pagesEntityConfig.taxonomies.enabled,
      types: pagesEntityConfig.taxonomies.types
    } : undefined
  },
  'posts': {
    name: 'posts',
    apiPath: postsEntityConfig.slug || 'posts',
    tableName: postsEntityConfig.slug,
    displayName: postsEntityConfig.names?.singular || postsEntityConfig.slug || 'posts',
    relativePath: 'posts',
    depth: 0,
    parent: null,
    children: [],
    hasComponents: true,
    hasHooks: false,
    hasMigrations: true,
    hasMessages: true,
    hasAssets: false,
    messagesPath: '@/contents/themes/barbercrm/entities/posts/messages',
    pluginContext: null,
    themeContext: { themeName: 'barbercrm' },
    isCore: false,
    source: 'theme',
    access: postsEntityConfig.access?.basePath ? {
      basePath: postsEntityConfig.access.basePath
    } : undefined,
    features: {
      enabled: postsEntityConfig.enabled !== false,
      canCreate: true,
      canEdit: true,
      canDelete: true,
      searchable: true,
      showInMenu: postsEntityConfig.ui?.dashboard?.showInMenu !== false
    },
    builder: postsEntityConfig.builder ? {
      enabled: postsEntityConfig.builder.enabled,
      sidebarFields: postsEntityConfig.builder.sidebarFields,
      sidebarFieldsConfig: postsEntityConfig.builder.sidebarFieldsConfig,
      showSlug: postsEntityConfig.builder.showSlug,
      public: postsEntityConfig.builder.public,
      seo: postsEntityConfig.builder.seo
    } : undefined,
    taxonomies: postsEntityConfig.taxonomies ? {
      enabled: postsEntityConfig.taxonomies.enabled,
      types: postsEntityConfig.taxonomies.types
    } : undefined
  },
  'products': {
    name: 'products',
    apiPath: productEntityConfig.slug || 'products',
    tableName: productEntityConfig.slug,
    displayName: productEntityConfig.names?.singular || productEntityConfig.slug || 'products',
    relativePath: 'products',
    depth: 0,
    parent: null,
    children: [],
    hasComponents: false,
    hasHooks: false,
    hasMigrations: true,
    hasMessages: true,
    hasAssets: false,
    messagesPath: '@/contents/themes/barbercrm/entities/products/messages',
    pluginContext: null,
    themeContext: { themeName: 'barbercrm' },
    isCore: false,
    source: 'theme',
    access: productEntityConfig.access?.basePath ? {
      basePath: productEntityConfig.access.basePath
    } : undefined,
    features: {
      enabled: productEntityConfig.enabled !== false,
      canCreate: true,
      canEdit: true,
      canDelete: true,
      searchable: true,
      showInMenu: productEntityConfig.ui?.dashboard?.showInMenu !== false
    },
    builder: productEntityConfig.builder ? {
      enabled: productEntityConfig.builder.enabled,
      sidebarFields: productEntityConfig.builder.sidebarFields,
      sidebarFieldsConfig: productEntityConfig.builder.sidebarFieldsConfig,
      showSlug: productEntityConfig.builder.showSlug,
      public: productEntityConfig.builder.public,
      seo: productEntityConfig.builder.seo
    } : undefined,
    taxonomies: productEntityConfig.taxonomies ? {
      enabled: productEntityConfig.taxonomies.enabled,
      types: productEntityConfig.taxonomies.types
    } : undefined
  },
  'services': {
    name: 'services',
    apiPath: serviceEntityConfig.slug || 'services',
    tableName: serviceEntityConfig.slug,
    displayName: serviceEntityConfig.names?.singular || serviceEntityConfig.slug || 'services',
    relativePath: 'services',
    depth: 0,
    parent: null,
    children: [],
    hasComponents: false,
    hasHooks: false,
    hasMigrations: true,
    hasMessages: true,
    hasAssets: false,
    messagesPath: '@/contents/themes/barbercrm/entities/services/messages',
    pluginContext: null,
    themeContext: { themeName: 'barbercrm' },
    isCore: false,
    source: 'theme',
    access: serviceEntityConfig.access?.basePath ? {
      basePath: serviceEntityConfig.access.basePath
    } : undefined,
    features: {
      enabled: serviceEntityConfig.enabled !== false,
      canCreate: true,
      canEdit: true,
      canDelete: true,
      searchable: true,
      showInMenu: serviceEntityConfig.ui?.dashboard?.showInMenu !== false
    },
    builder: serviceEntityConfig.builder ? {
      enabled: serviceEntityConfig.builder.enabled,
      sidebarFields: serviceEntityConfig.builder.sidebarFields,
      sidebarFieldsConfig: serviceEntityConfig.builder.sidebarFieldsConfig,
      showSlug: serviceEntityConfig.builder.showSlug,
      public: serviceEntityConfig.builder.public,
      seo: serviceEntityConfig.builder.seo
    } : undefined,
    taxonomies: serviceEntityConfig.taxonomies ? {
      enabled: serviceEntityConfig.taxonomies.enabled,
      types: serviceEntityConfig.taxonomies.types
    } : undefined
  },
  'tasks': {
    name: 'tasks',
    apiPath: taskEntityConfig.slug || 'tasks',
    tableName: taskEntityConfig.slug,
    displayName: taskEntityConfig.names?.singular || taskEntityConfig.slug || 'tasks',
    relativePath: 'tasks',
    depth: 0,
    parent: null,
    children: [],
    hasComponents: false,
    hasHooks: false,
    hasMigrations: true,
    hasMessages: true,
    hasAssets: false,
    messagesPath: '@/contents/themes/barbercrm/entities/tasks/messages',
    pluginContext: null,
    themeContext: { themeName: 'barbercrm' },
    isCore: false,
    source: 'theme',
    access: taskEntityConfig.access?.basePath ? {
      basePath: taskEntityConfig.access.basePath
    } : undefined,
    features: {
      enabled: taskEntityConfig.enabled !== false,
      canCreate: true,
      canEdit: true,
      canDelete: true,
      searchable: true,
      showInMenu: taskEntityConfig.ui?.dashboard?.showInMenu !== false
    },
    builder: taskEntityConfig.builder ? {
      enabled: taskEntityConfig.builder.enabled,
      sidebarFields: taskEntityConfig.builder.sidebarFields,
      sidebarFieldsConfig: taskEntityConfig.builder.sidebarFieldsConfig,
      showSlug: taskEntityConfig.builder.showSlug,
      public: taskEntityConfig.builder.public,
      seo: taskEntityConfig.builder.seo
    } : undefined,
    taxonomies: taskEntityConfig.taxonomies ? {
      enabled: taskEntityConfig.taxonomies.enabled,
      types: taskEntityConfig.taxonomies.types
    } : undefined
  }
}

// Slug to config name mapping for backwards compatibility
const SLUG_TO_CONFIG_MAP: Record<string, string> = {
      'patterns': 'patterns',
      'appointments': 'appointments',
      'barbers': 'barbers',
      'clients': 'clients',
      'pages': 'pages',
      'posts': 'posts',
      'products': 'products',
      'services': 'services',
      'tasks': 'tasks'
}

// ==================== Helper Functions ====================

/**
 * Get all registered entities
 */
export function getRegisteredEntities(): ClientEntityConfig[] {
  return Object.values(ENTITY_REGISTRY)
}

/**
 * Get entity by name
 */
export function getEntity(name: EntityName): ClientEntityConfig | undefined {
  return ENTITY_REGISTRY[name]
}

/**
 * Get entity by slug (for backwards compatibility)
 */
export function getEntityBySlug(slug: string): ClientEntityConfig | null {
  const configName = SLUG_TO_CONFIG_MAP[slug] || slug
  return ENTITY_REGISTRY[configName] || null
}

/**
 * Get API path for entity
 */
export function getEntityApiPath(entityType: string): string | null {
  // Check if this is a child entity first
  const childInfo = parseChildEntity(entityType)
  if (childInfo.isChild) {
    // For child entities, we need special handling
    return null
  }

  // Use entity registry lookup
  const entity = ENTITY_REGISTRY[entityType] || getEntityBySlug(entityType)
  return entity?.apiPath || null
}


/**
 * Check if entity exists
 */
export function hasEntity(name: string): boolean {
  return name in ENTITY_REGISTRY || getEntityBySlug(name) !== null
}

/**
 * Get entity display name
 */
export function getEntityDisplayName(slug: string): string {
  const entity = getEntityBySlug(slug) || ENTITY_REGISTRY[slug]
  return entity?.displayName || slug
}

// ==================== Client Meta System Adapter (Backwards Compatibility) ====================

/**
 * Client-safe meta system adapter for backwards compatibility
 */
export const clientMetaSystemAdapter = {
  /**
   * Get client-safe entity configuration
   */
  getEntityConfig: (entityType: string): ClientEntityConfig | undefined => {
    return getEntityBySlug(entityType) || ENTITY_REGISTRY[entityType]
  },

  /**
   * Get all client-safe entity configurations
   */
  getAllEntityConfigs: (): ClientEntityConfig[] => {
    return getRegisteredEntities()
  },

  /**
   * Check if entity exists in client-safe system
   */
  hasEntity: (entityType: string): boolean => {
    return hasEntity(entityType)
  },

  /**
   * Get API path for an entity (client-safe)
   */
  getApiPath: (entityType: string): string | null => {
    return getEntityApiPath(entityType)
  }
}

// ==================== Client Entity Registry (Backwards Compatibility) ====================

/**
 * Client entity registry for backwards compatibility
 */
export const clientEntityRegistry = {
  /**
   * Get entity config by slug (client-safe)
   */
  getBySlug: (slug: string): ClientEntityConfig | null => {
    return getEntityBySlug(slug)
  },

  /**
   * Get all available entity configs (client-safe)
   */
  getAll: (): ClientEntityConfig[] => {
    return getRegisteredEntities()
  },

  /**
   * Check if entity exists by slug (client-safe)
   */
  hasEntity: (slug: string): boolean => {
    return hasEntity(slug)
  },

  /**
   * Get entity display name by slug (client-safe)
   */
  getDisplayName: (slug: string): string => {
    return getEntityDisplayName(slug)
  }
}

/**
 * Client-safe version of ensureInitialized
 * Returns immediately since client config is static
 */
export async function ensureClientInitialized(): Promise<void> {
  // Client-side configs are always "initialized" since they're static
  return Promise.resolve()
}

// ==================== Child Entity Parsing ====================

/**
 * Parse child entity information (client-safe with baked-in discovery data)
 * Generated at build time with discovered parent-child relationships
 */
export function parseChildEntity(entityType: string): { isChild: boolean; parentEntity?: string; childType?: string } {
  // Baked-in parent entities discovered at build time
  const parentEntities: string[] = []

  // Baked-in child type mappings discovered at build time
  const childTypeMappings: Record<string, string> = {}

  // Check against discovered parent entities
  for (const parent of parentEntities) {
    if (entityType.startsWith(parent + '_')) {
      const childSingular = entityType.substring(parent.length + 1) // Remove "parent_"

      // Use discovered child type mappings
      const childType = childTypeMappings[childSingular] || childSingular + 's'

      return {
        isChild: true,
        parentEntity: parent,
        childType
      }
    }
  }

  return { isChild: false }
}

// ==================== Legacy Type Definitions ====================

export type ClientEntityType = EntityName
