/**
 * Auto-generated Unified Registry
 *
 * Generated at: 2026-05-31T11:38:05.467Z
 * Total contents: 24
 *
 * DO NOT EDIT - This file is auto-generated by scripts/build-registry.mjs
 */

export * from './plugin-registry'
export * from './entity-registry'
export * from './theme-registry'
export * from './template-registry'
export * from './middleware-registry'
export * from './scope-registry'
export * from './namespace-registry'
export * from './docs-registry'

import { PLUGIN_REGISTRY, PLUGIN_METADATA, type PluginName } from './plugin-registry'
import { ENTITY_REGISTRY, ENTITY_METADATA, type EntityName } from './entity-registry'
import { THEME_REGISTRY, THEME_METADATA, type ThemeName } from './theme-registry'
import { TEMPLATE_REGISTRY, TEMPLATE_METADATA, type TemplatePath } from './template-registry'
import { MIDDLEWARE_REGISTRY, MIDDLEWARE_METADATA } from './middleware-registry'
import { SCOPE_CONFIG, API_CONFIG } from './scope-registry'
import { NAMESPACE_CONFIG } from './namespace-registry'

/**
 * Unified Contents Registry - Ultra-fast access to all content types
 */
export const CONTENTS_REGISTRY = {
  plugins: PLUGIN_REGISTRY,
  entities: ENTITY_REGISTRY,
  themes: THEME_REGISTRY,
  templates: TEMPLATE_REGISTRY,
  middlewares: MIDDLEWARE_REGISTRY,
  scopes: SCOPE_CONFIG,
  api: API_CONFIG,
  namespaces: NAMESPACE_CONFIG
}

/**
 * Unified metadata for all content types
 */
export const CONTENTS_METADATA = {
  plugins: PLUGIN_METADATA,
  entities: ENTITY_METADATA,
  themes: THEME_METADATA,
  templates: TEMPLATE_METADATA,
  middlewares: MIDDLEWARE_METADATA,
  totals: {
    plugins: 0,
    entities: 9,
    themes: 1,
    templates: 14,
    middlewares: 0,
    total: 24
  },
  generatedAt: '2026-05-31T11:38:05.467Z'
}

/**
 * Unified type exports
 */
export type { PluginName, EntityName, ThemeName, TemplatePath }
