/**
 * Auto-generated Middleware Registry
 *
 * Generated at: 2026-05-31T16:00:45.258Z
 * Middlewares discovered: 0
 *
 * DO NOT EDIT - This file is auto-generated by scripts/build-registry.mjs
 *
 * Query functions moved to: @nextsparkjs/core/lib/services/middleware.service
 * Import from there for hasThemeMiddleware, executeThemeMiddleware, etc.
 */

import { NextRequest, NextResponse } from 'next/server'
import type { SessionUser } from '@nextsparkjs/core/lib/auth'



export interface MiddlewareRegistryEntry {
  themeName: string
  middleware: (request: NextRequest, coreSession?: SessionUser | null) => Promise<NextResponse | null> | NextResponse | null
  middlewarePath: string
  middlewareExportName: string
  exists: boolean
}

export const MIDDLEWARE_REGISTRY: Record<string, MiddlewareRegistryEntry> = {

}

export type ThemeName = never

/**
 * Middleware registry metadata
 */
export const MIDDLEWARE_METADATA = {
  totalMiddlewares: 0,
  themesWithMiddleware: 0,
  generatedAt: '2026-05-31T16:00:45.258Z',
  themes: []
}
