/**
 * Auto-generated Translation Namespace Registry
 *
 * Generated at: 2026-05-31T16:00:45.258Z
 * Core namespaces: 9
 * Entity namespaces: 0
 * Route strategies: 5
 * Entity paths: 0
 *
 * This file replaces hardcoded namespace configurations in i18n-integration.ts
 *
 * DO NOT EDIT - This file is auto-generated by scripts/build-registry.mjs
 */

export interface RouteNamespaceConfig {
  core: string[]
  entities: string[]
  strategy: string
}

export interface NamespaceConfig {
  core: string[]
  entities: string[]
  routes: Record<string, RouteNamespaceConfig>
  entityPaths: string[]
}

export const NAMESPACE_CONFIG: NamespaceConfig = {
  "core": [
    "common",
    "dashboard",
    "settings",
    "auth",
    "public",
    "validation",
    "superadmin",
    "admin",
    "teams"
  ],
  "entities": [],
  "routes": {
    "DASHBOARD_AUTHENTICATED": {
      "core": [
        "common",
        "dashboard",
        "settings",
        "public",
        "validation",
        "teams",
        "admin"
      ],
      "entities": [],
      "strategy": "DASHBOARD_AUTHENTICATED"
    },
    "AUTH_ONLY": {
      "core": [
        "common",
        "auth",
        "validation"
      ],
      "entities": [],
      "strategy": "AUTH_ONLY"
    },
    "PUBLIC_INITIAL": {
      "core": [
        "common",
        "public",
        "auth"
      ],
      "entities": [],
      "strategy": "PUBLIC_INITIAL"
    },
    "SUPERADMIN": {
      "core": [
        "common",
        "superadmin",
        "dashboard"
      ],
      "entities": [],
      "strategy": "SUPERADMIN"
    },
    "UNKNOWN_FALLBACK": {
      "core": [
        "common",
        "public"
      ],
      "entities": [],
      "strategy": "UNKNOWN_FALLBACK"
    }
  },
  "entityPaths": []
}

// ==================== Service Layer ====================
// Query functions have been moved to: @nextsparkjs/core/lib/services/namespace.service
// Import from there instead:
// import { NamespaceService } from '@nextsparkjs/core/lib/services/namespace.service'
// - NamespaceService.getCoreNamespaces() - Get core namespaces
// - NamespaceService.getEntityNamespaces() - Get entity namespaces
// - NamespaceService.getOptimizedNamespaces(strategy) - Get optimized namespaces
// - NamespaceService.detectRouteStrategy(pathname) - Detect route strategy
// - NamespaceService.getEntityPaths() - Get entity paths
