/**
 * Auto-generated Permissions Registry
 *
 * Generated at: 2026-05-31T16:00:45.259Z
 * Theme: barbercrm
 * Team permissions: 11
 * Feature permissions: 0
 * Entity permissions: 42
 *
 * This file provides pre-computed permissions data for O(1) runtime lookups.
 * All permission matrices are computed at build time.
 *
 * DO NOT EDIT - This file is auto-generated by scripts/build-registry.mjs
 *
 * Query functions moved to: @nextsparkjs/core/lib/services/permission.service
 * Import PermissionService for hasPermission, getRolePermissions, canDoAction, etc.
 */

import { CORE_PERMISSIONS_CONFIG } from '@nextsparkjs/core/lib/permissions/system'
import { APP_CONFIG_MERGED } from '@nextsparkjs/core/lib/config/config-sync'
import { PERMISSIONS_CONFIG_OVERRIDES } from '@/contents/themes/barbercrm/config/permissions.config'
import type { Permission, ResolvedPermission, PermissionUISection, RolesConfig, PermissionAction } from '@nextsparkjs/core/lib/permissions/types'

// ============================================================================
// BUILD-TIME CONSTANTS
// ============================================================================

// Entity permissions (from permissions.config.ts -> entities)
const ENTITY_PERMISSIONS = [
  {
    "id": "patterns.create",
    "label": "Create Patterns",
    "description": "Can create reusable patterns",
    "category": "Patterns",
    "roles": [
      "owner",
      "admin"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "patterns.read",
    "label": "View Patterns",
    "description": "Can view pattern details",
    "category": "Patterns",
    "roles": [
      "owner",
      "admin",
      "member"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "patterns.list",
    "label": "List Patterns",
    "description": "Can see the patterns list",
    "category": "Patterns",
    "roles": [
      "owner",
      "admin",
      "member"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "patterns.update",
    "label": "Edit Patterns",
    "description": "Can modify patterns",
    "category": "Patterns",
    "roles": [
      "owner",
      "admin"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "patterns.delete",
    "label": "Delete Patterns",
    "description": "Can delete patterns",
    "category": "Patterns",
    "roles": [
      "owner",
      "admin"
    ],
    "dangerous": true,
    "source": "theme"
  },
  {
    "id": "tasks.create",
    "label": "Create tasks",
    "description": "Can create new tasks",
    "category": "Tasks",
    "roles": [
      "owner",
      "admin",
      "member"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "tasks.read",
    "label": "View tasks",
    "description": "Can view task details",
    "category": "Tasks",
    "roles": [
      "owner",
      "admin",
      "member"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "tasks.list",
    "label": "List tasks",
    "description": "Can see the tasks list",
    "category": "Tasks",
    "roles": [
      "owner",
      "admin",
      "member"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "tasks.update",
    "label": "Edit tasks",
    "description": "Can modify task information",
    "category": "Tasks",
    "roles": [
      "owner",
      "admin",
      "member"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "tasks.delete",
    "label": "Delete tasks",
    "description": "Can delete tasks",
    "category": "Tasks",
    "roles": [
      "owner",
      "admin"
    ],
    "dangerous": true,
    "source": "theme"
  },
  {
    "id": "tasks.assign",
    "label": "Assign tasks",
    "description": "Can assign tasks to team members",
    "category": "Tasks",
    "roles": [
      "owner",
      "admin"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "pages.create",
    "label": "Create Pages",
    "description": "Can create new pages",
    "category": "Pages",
    "roles": [
      "owner",
      "admin"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "pages.read",
    "label": "View Pages",
    "description": "Can view page details",
    "category": "Pages",
    "roles": [
      "owner",
      "admin",
      "member"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "pages.list",
    "label": "List Pages",
    "description": "Can see the pages list",
    "category": "Pages",
    "roles": [
      "owner",
      "admin",
      "member"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "pages.update",
    "label": "Edit Pages",
    "description": "Can modify page content",
    "category": "Pages",
    "roles": [
      "owner",
      "admin"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "pages.delete",
    "label": "Delete Pages",
    "description": "Can delete pages",
    "category": "Pages",
    "roles": [
      "owner",
      "admin"
    ],
    "dangerous": true,
    "source": "theme"
  },
  {
    "id": "pages.publish",
    "label": "Publish Pages",
    "description": "Can publish pages to make them public",
    "category": "Pages",
    "roles": [
      "owner",
      "admin"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "clients.create",
    "label": "Create Clients",
    "description": "Can create new clients",
    "category": "Clients",
    "roles": [
      "owner",
      "admin",
      "member"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "clients.read",
    "label": "View Clients",
    "description": "Can view client details",
    "category": "Clients",
    "roles": [
      "owner",
      "admin",
      "member"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "clients.list",
    "label": "List Clients",
    "description": "Can see the clients list",
    "category": "Clients",
    "roles": [
      "owner",
      "admin",
      "member"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "clients.update",
    "label": "Edit Clients",
    "description": "Can modify client information",
    "category": "Clients",
    "roles": [
      "owner",
      "admin",
      "member"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "clients.delete",
    "label": "Delete Clients",
    "description": "Can delete clients",
    "category": "Clients",
    "roles": [
      "owner",
      "admin"
    ],
    "dangerous": true,
    "source": "theme"
  },
  {
    "id": "services.create",
    "label": "Create Services",
    "description": "Can create new services",
    "category": "Services",
    "roles": [
      "owner",
      "admin"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "services.read",
    "label": "View Services",
    "description": "Can view service details",
    "category": "Services",
    "roles": [
      "owner",
      "admin",
      "member"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "services.list",
    "label": "List Services",
    "description": "Can see the services list",
    "category": "Services",
    "roles": [
      "owner",
      "admin",
      "member"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "services.update",
    "label": "Edit Services",
    "description": "Can modify service information",
    "category": "Services",
    "roles": [
      "owner",
      "admin"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "services.delete",
    "label": "Delete Services",
    "description": "Can delete services",
    "category": "Services",
    "roles": [
      "owner",
      "admin"
    ],
    "dangerous": true,
    "source": "theme"
  },
  {
    "id": "barbers.create",
    "label": "Create Barbers",
    "description": "Can create new barbers",
    "category": "Barbers",
    "roles": [
      "owner",
      "admin"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "barbers.read",
    "label": "View Barbers",
    "description": "Can view barber details",
    "category": "Barbers",
    "roles": [
      "owner",
      "admin",
      "member"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "barbers.list",
    "label": "List Barbers",
    "description": "Can see the barbers list",
    "category": "Barbers",
    "roles": [
      "owner",
      "admin",
      "member"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "barbers.update",
    "label": "Edit Barbers",
    "description": "Can modify barber information",
    "category": "Barbers",
    "roles": [
      "owner",
      "admin"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "barbers.delete",
    "label": "Delete Barbers",
    "description": "Can delete barbers",
    "category": "Barbers",
    "roles": [
      "owner",
      "admin"
    ],
    "dangerous": true,
    "source": "theme"
  },
  {
    "id": "appointments.create",
    "label": "Create Appointments",
    "description": "Can create new appointments",
    "category": "Appointments",
    "roles": [
      "owner",
      "admin",
      "member"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "appointments.read",
    "label": "View Appointments",
    "description": "Can view appointment details",
    "category": "Appointments",
    "roles": [
      "owner",
      "admin",
      "member"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "appointments.list",
    "label": "List Appointments",
    "description": "Can see the appointments list",
    "category": "Appointments",
    "roles": [
      "owner",
      "admin",
      "member"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "appointments.update",
    "label": "Edit Appointments",
    "description": "Can modify appointment information",
    "category": "Appointments",
    "roles": [
      "owner",
      "admin",
      "member"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "appointments.delete",
    "label": "Delete Appointments",
    "description": "Can delete appointments",
    "category": "Appointments",
    "roles": [
      "owner",
      "admin"
    ],
    "dangerous": true,
    "source": "theme"
  },
  {
    "id": "products.create",
    "label": "Create Products",
    "description": "Can create new products",
    "category": "Products",
    "roles": [
      "owner",
      "admin",
      "member"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "products.read",
    "label": "View Products",
    "description": "Can view product details",
    "category": "Products",
    "roles": [
      "owner",
      "admin",
      "member"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "products.list",
    "label": "List Products",
    "description": "Can see the products list",
    "category": "Products",
    "roles": [
      "owner",
      "admin",
      "member"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "products.update",
    "label": "Edit Products",
    "description": "Can modify product information",
    "category": "Products",
    "roles": [
      "owner",
      "admin"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "products.delete",
    "label": "Delete Products",
    "description": "Can delete products",
    "category": "Products",
    "roles": [
      "owner",
      "admin"
    ],
    "dangerous": true,
    "source": "theme"
  }
] as unknown as ResolvedPermission[]

// Team permissions (from permissions.config.ts -> teams)
const TEAM_PERMISSIONS = [
  {
    "id": "team.view",
    "label": "View Team",
    "description": "Can view team details",
    "category": "Teams",
    "roles": [
      "owner",
      "admin",
      "member"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "team.members.view",
    "label": "View Members",
    "description": "Can see team member list",
    "category": "Teams",
    "roles": [
      "owner",
      "admin",
      "member"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "team.settings.view",
    "label": "View Settings",
    "description": "Can view team settings",
    "category": "Teams",
    "roles": [
      "owner",
      "admin",
      "member"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "team.billing.view",
    "label": "View Billing",
    "description": "Can view billing information",
    "category": "Teams",
    "roles": [
      "owner",
      "admin"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "team.edit",
    "label": "Edit Team",
    "description": "Can modify team name and details",
    "category": "Teams",
    "roles": [
      "owner",
      "admin"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "team.settings.edit",
    "label": "Edit Settings",
    "description": "Can modify team settings",
    "category": "Teams",
    "roles": [
      "owner",
      "admin"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "team.billing.manage",
    "label": "Manage Billing",
    "description": "Can manage subscriptions and payments",
    "category": "Teams",
    "roles": [
      "owner"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "team.members.invite",
    "label": "Invite Members",
    "description": "Can invite new team members",
    "category": "Teams",
    "roles": [
      "owner",
      "admin"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "team.members.remove",
    "label": "Remove Members",
    "description": "Can remove team members",
    "category": "Teams",
    "roles": [
      "owner",
      "admin"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "team.members.update_role",
    "label": "Update Roles",
    "description": "Can change member roles",
    "category": "Teams",
    "roles": [
      "owner",
      "admin"
    ],
    "dangerous": false,
    "source": "theme"
  },
  {
    "id": "team.delete",
    "label": "Delete Team",
    "description": "Can permanently delete the team",
    "category": "Teams",
    "roles": [
      "owner"
    ],
    "dangerous": true,
    "source": "theme"
  }
] as unknown as ResolvedPermission[]

// Feature permissions (from permissions.config.ts -> features, now using 'action')
const FEATURE_PERMISSIONS = [] as unknown as ResolvedPermission[]

// ============================================================================
// CUSTOM ROLES CONFIGURATION
// ============================================================================

/** Custom roles defined in permissions.config.ts */
export const CUSTOM_ROLES: RolesConfig = {}

// ============================================================================
// TEAM PERMISSIONS EXPORTS
// ============================================================================

/** Raw team permissions array (for UI) */
export const TEAM_PERMISSIONS_RAW: PermissionAction[] = PERMISSIONS_CONFIG_OVERRIDES.teams ?? []

/** Team permissions indexed by role (for O(1) lookup) */
export const TEAM_PERMISSIONS_BY_ROLE: Record<string, string[]> = (() => {
  const byRole: Record<string, string[]> = {}
  for (const perm of TEAM_PERMISSIONS_RAW) {
    for (const role of perm.roles) {
      if (!byRole[role]) byRole[role] = []
      byRole[role].push(perm.action)
    }
  }
  return byRole
})()

// ============================================================================
// RUNTIME MERGED PERMISSIONS (computed once on module load)
// ============================================================================

// Core team roles
const CORE_TEAM_ROLES = ['owner', 'admin', 'member', 'viewer'] as const

// Get available roles: core + custom from permissions.config.ts
export const AVAILABLE_ROLES: readonly string[] = [
  ...CORE_TEAM_ROLES,
  ...(CUSTOM_ROLES.additionalRoles ?? [])
]

// Role hierarchy (merged)
export const ROLE_HIERARCHY: Record<string, number> = {
  owner: 100,
  admin: 50,
  member: 10,
  viewer: 1,
  ...(CUSTOM_ROLES.hierarchy ?? {})
}

// Role display names (merged)
export const ROLE_DISPLAY_NAMES: Record<string, string> = {
  owner: 'common.teamRoles.owner',
  admin: 'common.teamRoles.admin',
  member: 'common.teamRoles.member',
  viewer: 'common.teamRoles.viewer',
  ...(CUSTOM_ROLES.displayNames ?? {})
}

// Role descriptions (merged)
export const ROLE_DESCRIPTIONS: Record<string, string> = {
  owner: 'Full team control, cannot be removed',
  admin: 'Manage team members and settings',
  member: 'Standard team access',
  viewer: 'Read-only access to team resources',
  ...(CUSTOM_ROLES.descriptions ?? {})
}

// Merge all permissions: core + teams + features + entities
function buildAllPermissions(): ResolvedPermission[] {
  const permissions: ResolvedPermission[] = []
  const addedIds = new Set<string>() // Track added IDs to prevent duplicates
  const disabledIds = new Set<string>(PERMISSIONS_CONFIG_OVERRIDES.disabled ?? [])
  const overrides = PERMISSIONS_CONFIG_OVERRIDES.overrides ?? {}

  // 1. Add core system permissions (highest priority)
  for (const perm of CORE_PERMISSIONS_CONFIG.systemPermissions) {
    if (disabledIds.has(perm.id)) continue

    const override = overrides[perm.id as keyof typeof overrides]
    permissions.push({
      ...perm,
      ...(override || {}),
      source: 'core',
      disabled: false
    } as ResolvedPermission)
    addedIds.add(perm.id)
  }

  // 2. Add team permissions
  for (const teamPerm of TEAM_PERMISSIONS) {
    if (disabledIds.has(teamPerm.id) || addedIds.has(teamPerm.id)) continue
    permissions.push({
      ...teamPerm,
      disabled: false
    })
    addedIds.add(teamPerm.id)
  }

  // 3. Add feature permissions (now using action instead of id)
  for (const featurePerm of FEATURE_PERMISSIONS) {
    if (disabledIds.has(featurePerm.id) || addedIds.has(featurePerm.id)) continue
    permissions.push({
      ...featurePerm,
      disabled: false
    })
    addedIds.add(featurePerm.id)
  }

  // 4. Add entity permissions
  for (const entityPerm of ENTITY_PERMISSIONS) {
    if (disabledIds.has(entityPerm.id) || addedIds.has(entityPerm.id)) continue
    permissions.push({
      ...entityPerm,
      disabled: false
    })
    addedIds.add(entityPerm.id)
  }

  return permissions
}

// Build permissions once on module load
export const ALL_RESOLVED_PERMISSIONS = buildAllPermissions()

// ============================================================================
// PRE-COMPUTED DATA STRUCTURES
// ============================================================================

// All permission IDs
export const ALL_PERMISSIONS: Permission[] = ALL_RESOLVED_PERMISSIONS.map(p => p.id as Permission)

// Set for O(1) existence check
export const ALL_PERMISSIONS_SET = new Set(ALL_PERMISSIONS)

// Permissions indexed by role (Set for O(1) lookup)
export const PERMISSIONS_BY_ROLE: Record<string, Set<Permission>> = {}

// Also as arrays for iteration
export const ROLE_PERMISSIONS_ARRAY: Record<string, Permission[]> = {}

// Build role matrices from roles
for (const role of AVAILABLE_ROLES) {
  if (role === 'owner') {
    // Owner has all permissions
    PERMISSIONS_BY_ROLE[role] = new Set(ALL_PERMISSIONS)
    ROLE_PERMISSIONS_ARRAY[role] = [...ALL_PERMISSIONS]
  } else {
    const rolePerms: Permission[] = []
    for (const perm of ALL_RESOLVED_PERMISSIONS) {
      if (perm.roles?.includes(role as any)) {
        rolePerms.push(perm.id as Permission)
      }
    }
    PERMISSIONS_BY_ROLE[role] = new Set(rolePerms)
    ROLE_PERMISSIONS_ARRAY[role] = rolePerms
  }
}

// NOTE: Custom roles (like 'editor') get their permissions via roles in permissions.config.ts
// The TEAM_ROLE_PERMISSIONS hack has been removed in favor of centralized permission definitions.

// Permissions indexed by category
export const PERMISSIONS_BY_CATEGORY: Record<string, ResolvedPermission[]> = {}
for (const perm of ALL_RESOLVED_PERMISSIONS) {
  if (!PERMISSIONS_BY_CATEGORY[perm.category]) {
    PERMISSIONS_BY_CATEGORY[perm.category] = []
  }
  PERMISSIONS_BY_CATEGORY[perm.category].push(perm)
}

// Full matrix for UI (Sector7)
export const FULL_MATRIX: Record<Permission, Record<string, boolean>> = {} as any
for (const perm of ALL_RESOLVED_PERMISSIONS) {
  FULL_MATRIX[perm.id as Permission] = {}
  for (const role of AVAILABLE_ROLES) {
    FULL_MATRIX[perm.id as Permission][role] = PERMISSIONS_BY_ROLE[role]?.has(perm.id as Permission) ?? false
  }
}

// UI Sections
export const UI_SECTIONS: PermissionUISection[] = [
  // Core sections
  ...CORE_PERMISSIONS_CONFIG.uiSections,
  // Theme sections
  ...(PERMISSIONS_CONFIG_OVERRIDES.uiSections ?? []),
  // Entity section (auto-generated)
  {
    id: 'entities',
    label: 'Entities',
    description: 'Entity-specific permissions',
    categories: [...new Set(ENTITY_PERMISSIONS.map(p => p.category))]
  }
]

// ============================================================================
// METADATA
// ============================================================================

export const PERMISSIONS_METADATA = {
  totalPermissions: ALL_PERMISSIONS.length,
  corePermissions: CORE_PERMISSIONS_CONFIG.systemPermissions.length,
  teamPermissions: TEAM_PERMISSIONS.length,
  featurePermissions: FEATURE_PERMISSIONS.length,
  entityPermissions: ENTITY_PERMISSIONS.length,
  customRoles: CUSTOM_ROLES.additionalRoles?.length ?? 0,
  availableRoles: AVAILABLE_ROLES.length,
  categories: Object.keys(PERMISSIONS_BY_CATEGORY).length,
  generatedAt: '2026-05-31T16:00:45.259Z',
  theme: 'barbercrm'
}
