/**
 * Auto-generated Plugin Registry - SERVER ONLY
 *
 * Generated at: 2026-05-31T11:38:05.451Z
 * Plugins discovered: 0
 *
 * WARNING: This registry includes server-side route handlers and Node.js dependencies.
 * For client-side usage, import from './plugin-registry.client' instead.
 *
 * DO NOT EDIT - This file is auto-generated by scripts/build-registry.mjs
 */

import 'server-only'


import type { PluginConfig } from '@nextsparkjs/core/types/plugin'

// Re-export PluginConfig for external use
export type { PluginConfig }

export interface RouteFileEndpoint {
  path: string
  filePath: string
  relativePath: string
  methods: string[]
  isRouteFile: boolean
}

export interface RouteHandler {
  plugin: string
  methods: string[]
  handlers: Record<string, any>
}

export interface PluginEntity {
  name: string
  exportName: string
  configPath: string
  actualConfigFile: string
  relativePath: string
  depth: number
  parent: string | null
  children: string[]
  hasComponents: boolean
  hasHooks: boolean
  hasMigrations: boolean
  hasMessages: boolean
  hasAssets: boolean
  messagesPath: string
  pluginContext: { pluginName: string } | null
}

export interface PluginSettingsArea {
  area: string
  hasMigrations: boolean
}

export interface PluginRegistryEntry {
  name: string
  config: PluginConfig
  hasAPI: boolean
  apiPath: string | null
  routeFiles: RouteFileEndpoint[]
  entities: PluginEntity[]
  settings: PluginSettingsArea[]
  hasMessages: boolean
  hasAssets: boolean
}

export const PLUGIN_REGISTRY: Record<string, PluginRegistryEntry> = {

}

export const ROUTE_METADATA = {

}

export type PluginName = keyof typeof PLUGIN_REGISTRY

// ==================== Plugin Page Components (Server-Only) ====================
// Maps plugin names to their devtools page components.
// Used by app/devtools/plugins/[plugin]/page.tsx to render plugin settings pages.
// Auto-generated: add plugin.pages.server.ts to a plugin to contribute a devtools page.

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const PLUGIN_DEVTOOLS_PAGES: Record<string, any> = {

}

// Maps plugin names to their superadmin page components.
// Used by app/superadmin/plugins/[plugin]/page.tsx to render plugin settings pages.
// Export 'superadminPage' from plugin.pages.server.ts to contribute a superadmin page.

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const PLUGIN_SUPERADMIN_PAGES: Record<string, any> = {

}

// ==================== Navigation Helpers ====================
/**
 * Returns all nav items for a given area from all registered plugins.
 * Safe to call in server components.
 */
export function getPluginNavItems(area: 'devtools' | 'superadmin') {
  return Object.values(PLUGIN_REGISTRY).flatMap(
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (entry) => ((entry.config as any).navigation)?.[area]?.items ?? []
  )
}

/**
 * Returns the PLUGIN_DEVTOOLS_PAGES map for use in core page components.
 * Allows the core's PluginDevtoolsPage component to resolve plugin pages
 * without importing the registry directly (which would be a circular dep).
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function getPluginDevtoolsPages(): Record<string, any> {
  return PLUGIN_DEVTOOLS_PAGES
}

// ==================== Service Layer ====================
// Query functions have been moved to: @nextsparkjs/core/lib/services/plugin.service
// import { PluginService, usePlugin } from '@nextsparkjs/core/lib/services'

/**
 * Plugin registry metadata
 */
export const PLUGIN_METADATA = {
  totalPlugins: 0,
  pluginsWithAPI: 0,
  pluginsWithEntities: 0,
  pluginsWithMessages: 0,
  pluginsWithAssets: 0,
  totalRouteFiles: 0,
  totalPluginEntities: 0,
  generatedAt: '2026-05-31T11:38:05.451Z',
  plugins: []
}
