/**
 * Client-Safe Plugin Registry
 *
 * Generated at: 2026-05-31T11:38:05.451Z
 * Plugins discovered: 0
 *
 * This is the client-safe version of the plugin registry.
 * Contains only configuration data, no server-side route handlers.
 *
 * DO NOT EDIT - This file is auto-generated by scripts/build-registry.mjs
 */


import type { PluginNavItem } from '@nextsparkjs/core/types/plugin'

export interface ClientPluginNavSection {
  sectionLabel?: string
  items: PluginNavItem[]
}

export interface ClientPluginSettingsArea {
  area: string
  hasMigrations: boolean
}

export interface ClientPluginConfig {
  name: string
  hasAPI: boolean
  apiPath: string | null
  entities: string[]
  settings: ClientPluginSettingsArea[]
  hasMessages: boolean
  hasAssets: boolean
  navigation?: {
    devtools?: ClientPluginNavSection
    superadmin?: ClientPluginNavSection
  }
}

export interface ClientPluginRegistry {
  [key: string]: ClientPluginConfig
}

// Plugin name type for type safety
export type PluginName = never

// Client-safe plugin registry (no server-side imports)
export const PLUGIN_REGISTRY: ClientPluginRegistry = {

}

// Helper functions
export function getPlugin(name: string): ClientPluginConfig | null {
  return (PLUGIN_REGISTRY as any)[name] || null
}

export function getAllPlugins(): ClientPluginConfig[] {
  return Object.values(PLUGIN_REGISTRY)
}

export function hasPlugin(name: string): boolean {
  return name in PLUGIN_REGISTRY
}

/**
 * Returns all nav items for a given area from all registered plugins.
 * Safe to call in server components (returns serializable data).
 */
export function getPluginNavItems(area: 'devtools' | 'superadmin'): PluginNavItem[] {
  return Object.values(PLUGIN_REGISTRY).flatMap(
    (plugin) => plugin.navigation?.[area]?.items ?? []
  )
}

// React hook for using plugin in components
export function usePlugin(name: PluginName): ClientPluginConfig | null {
  return getPlugin(name)
}
