/**
 * Auto-generated Route Handlers Registry
 *
 * Generated at: 2026-05-31T16:00:45.247Z
 * Core routes: 31
 * Entity routes: 18
 * Theme routes: 0
 * Plugin routes: 0
 * Total routes: 49
 *
 * DO NOT EDIT - This file is auto-generated by scripts/build-registry.mjs
 *
 * ZERO runtime dynamic imports - all route handlers resolved at build time.
 * Provides ~17,255x performance improvement over runtime I/O.
 */

import type { NextRequest, NextResponse } from 'next/server'

// No route imports needed

/**
 * Route handler type definition
 */
export type RouteHandler = (
  request: NextRequest,
  context: { params: Promise<any> }
) => Promise<NextResponse>

/**
 * API Route entry for documentation
 */
export interface ApiRouteEntry {
  path: string
  methods: string[]
  category: 'core' | 'entity' | 'theme' | 'plugin'
  source?: string
  subcategory?: string
}

/**
 * Theme Route Handlers Registry
 * Access: THEME_ROUTE_HANDLERS['theme-name/route-path'][HTTP_METHOD]
 */
export const THEME_ROUTE_HANDLERS: Record<string, Record<string, RouteHandler | undefined>> = {
  // No theme routes discovered
}

/**
 * Plugin Route Handlers Registry
 * Access: PLUGIN_ROUTE_HANDLERS['plugin-name/route-path'][HTTP_METHOD]
 */
export const PLUGIN_ROUTE_HANDLERS: Record<string, Record<string, RouteHandler | undefined>> = {
  // No plugin routes discovered
}

// ==================== API ROUTES METADATA ====================
// Data-only registry for documentation and devtools
// Use ApiRoutesService for queries

/**
 * API Routes Metadata
 * Complete listing of all available API endpoints grouped by category
 */
export const API_ROUTES_METADATA: {
  core: ApiRouteEntry[]
  entities: ApiRouteEntry[]
  theme: ApiRouteEntry[]
  plugins: ApiRouteEntry[]
} = {
  core: [
    { path: '/api/v1/api-keys', methods: ["OPTIONS","GET","POST"], category: 'core', subcategory: 'api-keys' },
    { path: '/api/v1/auth/signup-with-invite', methods: ["OPTIONS","POST"], category: 'core', subcategory: 'auth' },
    { path: '/api/v1/billing/cancel', methods: ["POST"], category: 'core', subcategory: 'billing' },
    { path: '/api/v1/billing/change-plan', methods: ["POST"], category: 'core', subcategory: 'billing' },
    { path: '/api/v1/billing/check-action', methods: ["POST"], category: 'core', subcategory: 'billing' },
    { path: '/api/v1/billing/checkout', methods: ["POST"], category: 'core', subcategory: 'billing' },
    { path: '/api/v1/billing/plans', methods: ["GET","POST"], category: 'core', subcategory: 'billing' },
    { path: '/api/v1/billing/portal', methods: ["POST"], category: 'core', subcategory: 'billing' },
    { path: '/api/v1/billing/webhooks/polar', methods: ["POST"], category: 'core', subcategory: 'billing' },
    { path: '/api/v1/billing/webhooks/stripe', methods: ["POST"], category: 'core', subcategory: 'billing' },
    { path: '/api/v1/blocks', methods: ["GET"], category: 'core', subcategory: 'blocks' },
    { path: '/api/v1/blocks/validate', methods: ["POST"], category: 'core', subcategory: 'blocks' },
    { path: '/api/v1/cron/process', methods: ["GET"], category: 'core', subcategory: 'other' },
    { path: '/api/v1/devtools/blocks', methods: ["OPTIONS","GET"], category: 'core', subcategory: 'other' },
    { path: '/api/v1/devtools/docs', methods: ["GET"], category: 'core', subcategory: 'other' },
    { path: '/api/v1/devtools/features', methods: ["OPTIONS","GET"], category: 'core', subcategory: 'other' },
    { path: '/api/v1/devtools/flows', methods: ["OPTIONS","GET"], category: 'core', subcategory: 'other' },
    { path: '/api/v1/devtools/scheduled-actions', methods: ["OPTIONS","GET","POST"], category: 'core', subcategory: 'other' },
    { path: '/api/v1/devtools/scheduled-actions/run', methods: ["OPTIONS","POST"], category: 'core', subcategory: 'other' },
    { path: '/api/v1/devtools/testing', methods: ["OPTIONS","GET"], category: 'core', subcategory: 'other' },
    { path: '/api/v1/media/check-duplicates', methods: ["POST"], category: 'core', subcategory: 'media' },
    { path: '/api/v1/media', methods: ["GET"], category: 'core', subcategory: 'media' },
    { path: '/api/v1/media/upload', methods: ["POST","GET"], category: 'core', subcategory: 'media' },
    { path: '/api/v1/media-tags', methods: ["GET","POST"], category: 'core', subcategory: 'other' },
    { path: '/api/v1/plugin', methods: ["GET"], category: 'core', subcategory: 'plugin' },
    { path: '/api/v1/post-categories', methods: ["GET","POST"], category: 'core', subcategory: 'content' },
    { path: '/api/v1/team-invitations', methods: ["OPTIONS","GET"], category: 'core', subcategory: 'teams' },
    { path: '/api/v1/teams', methods: ["OPTIONS","GET","POST"], category: 'core', subcategory: 'teams' },
    { path: '/api/v1/teams/switch', methods: ["OPTIONS","POST"], category: 'core', subcategory: 'teams' },
    { path: '/api/v1/theme', methods: ["GET"], category: 'core', subcategory: 'theme' },
    { path: '/api/v1/users', methods: ["OPTIONS","GET","POST"], category: 'core', subcategory: 'users' }
  ],
  entities: [
    { path: '/api/v1/patterns', methods: ["GET","POST"], category: 'entity', source: 'patterns' },
    { path: '/api/v1/patterns/[id]', methods: ["GET","PATCH","DELETE"], category: 'entity', source: 'patterns' },
    { path: '/api/v1/appointments', methods: ["GET","POST"], category: 'entity', source: 'appointments' },
    { path: '/api/v1/appointments/[id]', methods: ["GET","PATCH","DELETE"], category: 'entity', source: 'appointments' },
    { path: '/api/v1/barbers', methods: ["GET","POST"], category: 'entity', source: 'barbers' },
    { path: '/api/v1/barbers/[id]', methods: ["GET","PATCH","DELETE"], category: 'entity', source: 'barbers' },
    { path: '/api/v1/clients', methods: ["GET","POST"], category: 'entity', source: 'clients' },
    { path: '/api/v1/clients/[id]', methods: ["GET","PATCH","DELETE"], category: 'entity', source: 'clients' },
    { path: '/api/v1/pages', methods: ["GET","POST"], category: 'entity', source: 'pages' },
    { path: '/api/v1/pages/[id]', methods: ["GET","PATCH","DELETE"], category: 'entity', source: 'pages' },
    { path: '/api/v1/posts', methods: ["GET","POST"], category: 'entity', source: 'posts' },
    { path: '/api/v1/posts/[id]', methods: ["GET","PATCH","DELETE"], category: 'entity', source: 'posts' },
    { path: '/api/v1/products', methods: ["GET","POST"], category: 'entity', source: 'products' },
    { path: '/api/v1/products/[id]', methods: ["GET","PATCH","DELETE"], category: 'entity', source: 'products' },
    { path: '/api/v1/services', methods: ["GET","POST"], category: 'entity', source: 'services' },
    { path: '/api/v1/services/[id]', methods: ["GET","PATCH","DELETE"], category: 'entity', source: 'services' },
    { path: '/api/v1/tasks', methods: ["GET","POST"], category: 'entity', source: 'tasks' },
    { path: '/api/v1/tasks/[id]', methods: ["GET","PATCH","DELETE"], category: 'entity', source: 'tasks' }
  ],
  theme: [
    // No theme routes discovered
  ],
  plugins: [
    // No plugin routes discovered
  ]
}

/**
 * API Routes Summary
 * Quick stats about available routes
 */
export const API_ROUTES_SUMMARY = {
  totalRoutes: 49,
  byCategory: {
    core: 31,
    entities: 18,
    theme: 0,
    plugins: 0
  },
  generatedAt: '2026-05-31T16:00:45.248Z'
}

// ==================== Service Layer ====================
// Query functions have been moved to: @nextsparkjs/core/lib/services/route-handler.service
// For route handler queries, import:
// import { RouteHandlerService } from '@nextsparkjs/core/lib/services/route-handler.service'
//
// For API routes metadata queries, import:
// import { ApiRoutesService } from '@nextsparkjs/core/lib/services/api-routes.service'
