/**
 * Auto-generated Scheduled Actions Registry (Server-Only)
 *
 * Generated at: 2026-05-31T11:38:05.465Z
 * Themes with scheduled actions: 0
 *
 * This registry provides access to theme-specific scheduled action initializers.
 * It is kept separate from theme-registry.ts because scheduled actions contain
 * server-only code (database access, etc.) that cannot be imported by client components.
 *
 * DO NOT EDIT - This file is auto-generated by scripts/build-registry.mjs
 */

import 'server-only'


/**
 * Type for scheduled actions module
 */
export interface ScheduledActionsModule {
  registerAllHandlers: () => void
  registerRecurringActions: () => Promise<void>
}

/**
 * Registry of theme scheduled action modules
 * Auto-generated based on discovered themes with hasScheduledActions: true
 */
export const SCHEDULED_ACTIONS_REGISTRY: Record<string, ScheduledActionsModule> = {

}

/**
 * Registry metadata
 */
export const SCHEDULED_ACTIONS_METADATA = {
  totalThemes: 0,
  themes: [],
  generatedAt: '2026-05-31T11:38:05.465Z'
}
