/**
 * Auto-generated API Scope Registry
 *
 * Generated at: 2026-05-31T11:38:05.464Z
 * Base scopes: 0
 * Role configurations: 4
 * Flag configurations: 4
 * Allowed filters: 4
 *
 * This file replaces hardcoded scope configurations in helpers.ts
 *
 * DO NOT EDIT - This file is auto-generated by scripts/build-registry.mjs
 */

export interface ScopeConfig {
  base: string[]
  roles: Record<string, string[]>
  flags: Record<string, string[]>
  restrictions: Record<string, { remove?: string[], allow_only?: string[] }>
}

export interface ApiConfig {
  filters: {
    allowed: string[]
  }
  entityPaths: string[]
}

export const SCOPE_CONFIG: ScopeConfig = {
  "base": [],
  "roles": {
    "superadmin": [
      "admin:users",
      "tasks:delete",
      "products:write",
      "products:delete"
    ],
    "admin": [
      "admin:users",
      "tasks:delete",
      "products:write",
      "products:delete"
    ],
    "manager": [],
    "member": []
  },
  "flags": {
    "beta_tester": [
      "beta:features"
    ],
    "vip": [
      "vip:features",
      "advanced:export"
    ],
    "early_adopter": [
      "early:features"
    ],
    "power_user": [
      "advanced:features",
      "bulk:operations"
    ]
  },
  "restrictions": {
    "restricted": {
      "remove": [
        "delete",
        "admin"
      ]
    },
    "limited_access": {
      "allow_only": [
        "read",
        "tasks:write"
      ]
    }
  }
}

export const API_CONFIG: ApiConfig = {
  "filters": {
    "allowed": [
      "status",
      "role",
      "completed",
      "userId"
    ]
  },
  "entityPaths": []
}

// ==================== Service Layer ====================
// Query functions have been moved to: @nextsparkjs/core/lib/services/scope.service
// Import from there instead:
//
// import { ScopeService } from '@nextsparkjs/core/lib/services/scope.service'
//
// Available methods:
// - ScopeService.getBaseScopes() - Get base scopes
// - ScopeService.getRoleScopes(role) - Get role scopes
// - ScopeService.getFlagScopes(flag) - Get flag scopes
// - ScopeService.getAllowedFilters() - Get allowed filters
// - ScopeService.getRestrictionRules(flag) - Get restriction rules
// - ScopeService.getEntityApiPaths() - Get entity API paths
// - ScopeService.getRoles() - Get all role names
// - ScopeService.getFlags() - Get all flag names
// - ScopeService.hasRole(role) - Check if role exists
// - ScopeService.hasFlag(flag) - Check if flag exists
// - ScopeService.getScopeConfig() - Get full scope config
// - ScopeService.getApiConfig() - Get full API config
