/**
 * Auto-generated Client Template Registry
 *
 * Generated at: 2026-05-31T11:38:05.450Z
 * Client-compatible templates: 9
 *
 * DO NOT EDIT - This file is auto-generated by scripts/build-registry.mjs
 */

'use client'

import { ComponentType } from 'react'
import { isProtectedPath } from '@nextsparkjs/core/config/protected-paths'

import ClientTemplate_0 from '@/contents/themes/barbercrm/templates/(public)/layout'
import ClientTemplate_1 from '@/contents/themes/barbercrm/templates/dashboard/(main)/appointments/page'
import ClientTemplate_2 from '@/contents/themes/barbercrm/templates/dashboard/(main)/barbers/[id]/page'
import ClientTemplate_3 from '@/contents/themes/barbercrm/templates/dashboard/(main)/calendar/page'
import ClientTemplate_4 from '@/contents/themes/barbercrm/templates/dashboard/(main)/clients/[id]/page'
import ClientTemplate_5 from '@/contents/themes/barbercrm/templates/dashboard/(main)/clients-alert/page'
import ClientTemplate_6 from '@/contents/themes/barbercrm/templates/dashboard/(main)/customize/page'
import ClientTemplate_7 from '@/contents/themes/barbercrm/templates/dashboard/(main)/products/page'
import ClientTemplate_8 from '@/contents/themes/barbercrm/templates/dashboard/settings/shop/page'

// Client-safe registry with static imports (auto-generated)
const CLIENT_TEMPLATE_REGISTRY: Record<string, ComponentType<any>> = {
  'app/(public)/layout.tsx': ClientTemplate_0,
  'app/dashboard/(main)/appointments/page.tsx': ClientTemplate_1,
  'app/dashboard/(main)/barbers/[id]/page.tsx': ClientTemplate_2,
  'app/dashboard/(main)/calendar/page.tsx': ClientTemplate_3,
  'app/dashboard/(main)/clients/[id]/page.tsx': ClientTemplate_4,
  'app/dashboard/(main)/clients-alert/page.tsx': ClientTemplate_5,
  'app/dashboard/(main)/customize/page.tsx': ClientTemplate_6,
  'app/dashboard/(main)/products/page.tsx': ClientTemplate_7,
  'app/dashboard/settings/shop/page.tsx': ClientTemplate_8
}

/**
 * Check if template override exists (client-safe)
 */
export function hasTemplateOverrideClient(appPath: string): boolean {
  return appPath in CLIENT_TEMPLATE_REGISTRY
}

/**
 * Get template component with static import (client-safe)
 * Use this in client components to avoid metadata conflicts
 */
export function getTemplateOrDefaultClient<T extends ComponentType<any>>(
  appPath: string,
  defaultComponent: T
): T {
  // Check if path is protected
  if (isProtectedPath(appPath)) {
    return defaultComponent
  }

  // Check if template override exists
  if (!hasTemplateOverrideClient(appPath)) {
    return defaultComponent
  }

  // Return statically imported template component
  const TemplateComponent = CLIENT_TEMPLATE_REGISTRY[appPath]
  return TemplateComponent as T
}

/**
 * Higher-order component for template overrides (client-safe)
 */
export function withTemplateOverrideForClient<P extends object>(appPath: string) {
  return function<T extends ComponentType<P>>(WrappedComponent: T): T {
    return getTemplateOrDefaultClient(appPath, WrappedComponent)
  }
}
