/**
 * Auto-generated Template Registry
 *
 * Generated at: 2026-05-31T16:00:45.253Z
 * Templates discovered: 14
 * App paths with overrides: 14
 *
 * DO NOT EDIT - This file is auto-generated by scripts/build-registry.mjs
 */

import Template_0 from '@/contents/themes/barbercrm/templates/(public)/layout'
import Template_1 from '@/contents/themes/barbercrm/templates/(public)/loading'
import Template_2 from '@/contents/themes/barbercrm/templates/(public)/page'
import Template_3 from '@/contents/themes/barbercrm/templates/(public)/support/page'
import Template_4 from '@/contents/themes/barbercrm/templates/dashboard/(main)/appointments/page'
import Template_5 from '@/contents/themes/barbercrm/templates/dashboard/(main)/barbers/[id]/page'
import Template_6 from '@/contents/themes/barbercrm/templates/dashboard/(main)/calendar/page'
import Template_7 from '@/contents/themes/barbercrm/templates/dashboard/(main)/clients/[id]/page'
import Template_8 from '@/contents/themes/barbercrm/templates/dashboard/(main)/clients-alert/page'
import Template_9 from '@/contents/themes/barbercrm/templates/dashboard/(main)/customize/page'
import Template_10 from '@/contents/themes/barbercrm/templates/dashboard/(main)/products/page'
import Template_11 from '@/contents/themes/barbercrm/templates/dashboard/analytics/loading'
import Template_12 from '@/contents/themes/barbercrm/templates/dashboard/analytics/page'
import Template_13 from '@/contents/themes/barbercrm/templates/dashboard/settings/shop/page'

export interface TemplateOverride {
  name: string
  themeName: string
  templateType: string
  fileName: string
  relativePath: string
  appPath: string
  templatePath: string
  priority: number
  metadata?: any
}

export interface TemplateRegistryEntry {
  appPath: string
  component: any
  template: TemplateOverride
  alternatives: TemplateOverride[]
}

export const TEMPLATE_REGISTRY: Record<string, TemplateRegistryEntry> = {
  'app/(public)/layout.tsx': {
    appPath: 'app/(public)/layout.tsx',
    component: Template_0,
    template:     {
        "name": "(public)/layout",
        "themeName": "barbercrm",
        "templateType": "layout",
        "fileName": "layout.tsx",
        "relativePath": "(public)/layout.tsx",
        "appPath": "app/(public)/layout.tsx",
        "templatePath": "@/contents/themes/barbercrm/templates/(public)/layout.tsx",
        "priority": 112,
        "metadata": null
    },
    alternatives:     []
  },
  'app/(public)/loading.tsx': {
    appPath: 'app/(public)/loading.tsx',
    component: Template_1,
    template:     {
        "name": "(public)/loading",
        "themeName": "barbercrm",
        "templateType": "loading",
        "fileName": "loading.tsx",
        "relativePath": "(public)/loading.tsx",
        "appPath": "app/(public)/loading.tsx",
        "templatePath": "@/contents/themes/barbercrm/templates/(public)/loading.tsx",
        "priority": 102,
        "metadata": null
    },
    alternatives:     []
  },
  'app/(public)/page.tsx': {
    appPath: 'app/(public)/page.tsx',
    component: Template_2,
    template:     {
        "name": "(public)/page",
        "themeName": "barbercrm",
        "templateType": "page",
        "fileName": "page.tsx",
        "relativePath": "(public)/page.tsx",
        "appPath": "app/(public)/page.tsx",
        "templatePath": "@/contents/themes/barbercrm/templates/(public)/page.tsx",
        "priority": 107,
        "metadata": null
    },
    alternatives:     []
  },
  'app/(public)/support/page.tsx': {
    appPath: 'app/(public)/support/page.tsx',
    component: Template_3,
    template:     {
        "name": "(public)/support/page",
        "themeName": "barbercrm",
        "templateType": "page",
        "fileName": "page.tsx",
        "relativePath": "(public)/support/page.tsx",
        "appPath": "app/(public)/support/page.tsx",
        "templatePath": "@/contents/themes/barbercrm/templates/(public)/support/page.tsx",
        "priority": 109,
        "metadata": null
    },
    alternatives:     []
  },
  'app/dashboard/(main)/appointments/page.tsx': {
    appPath: 'app/dashboard/(main)/appointments/page.tsx',
    component: Template_4,
    template:     {
        "name": "dashboard/(main)/appointments/page",
        "themeName": "barbercrm",
        "templateType": "page",
        "fileName": "page.tsx",
        "relativePath": "dashboard/(main)/appointments/page.tsx",
        "appPath": "app/dashboard/(main)/appointments/page.tsx",
        "templatePath": "@/contents/themes/barbercrm/templates/dashboard/(main)/appointments/page.tsx",
        "priority": 111,
        "metadata": null
    },
    alternatives:     []
  },
  'app/dashboard/(main)/barbers/[id]/page.tsx': {
    appPath: 'app/dashboard/(main)/barbers/[id]/page.tsx',
    component: Template_5,
    template:     {
        "name": "dashboard/(main)/barbers/[id]/page",
        "themeName": "barbercrm",
        "templateType": "page",
        "fileName": "page.tsx",
        "relativePath": "dashboard/(main)/barbers/[id]/page.tsx",
        "appPath": "app/dashboard/(main)/barbers/[id]/page.tsx",
        "templatePath": "@/contents/themes/barbercrm/templates/dashboard/(main)/barbers/[id]/page.tsx",
        "priority": 113,
        "metadata": null
    },
    alternatives:     []
  },
  'app/dashboard/(main)/calendar/page.tsx': {
    appPath: 'app/dashboard/(main)/calendar/page.tsx',
    component: Template_6,
    template:     {
        "name": "dashboard/(main)/calendar/page",
        "themeName": "barbercrm",
        "templateType": "page",
        "fileName": "page.tsx",
        "relativePath": "dashboard/(main)/calendar/page.tsx",
        "appPath": "app/dashboard/(main)/calendar/page.tsx",
        "templatePath": "@/contents/themes/barbercrm/templates/dashboard/(main)/calendar/page.tsx",
        "priority": 111,
        "metadata": null
    },
    alternatives:     []
  },
  'app/dashboard/(main)/clients/[id]/page.tsx': {
    appPath: 'app/dashboard/(main)/clients/[id]/page.tsx',
    component: Template_7,
    template:     {
        "name": "dashboard/(main)/clients/[id]/page",
        "themeName": "barbercrm",
        "templateType": "page",
        "fileName": "page.tsx",
        "relativePath": "dashboard/(main)/clients/[id]/page.tsx",
        "appPath": "app/dashboard/(main)/clients/[id]/page.tsx",
        "templatePath": "@/contents/themes/barbercrm/templates/dashboard/(main)/clients/[id]/page.tsx",
        "priority": 113,
        "metadata": null
    },
    alternatives:     []
  },
  'app/dashboard/(main)/clients-alert/page.tsx': {
    appPath: 'app/dashboard/(main)/clients-alert/page.tsx',
    component: Template_8,
    template:     {
        "name": "dashboard/(main)/clients-alert/page",
        "themeName": "barbercrm",
        "templateType": "page",
        "fileName": "page.tsx",
        "relativePath": "dashboard/(main)/clients-alert/page.tsx",
        "appPath": "app/dashboard/(main)/clients-alert/page.tsx",
        "templatePath": "@/contents/themes/barbercrm/templates/dashboard/(main)/clients-alert/page.tsx",
        "priority": 111,
        "metadata": null
    },
    alternatives:     []
  },
  'app/dashboard/(main)/customize/page.tsx': {
    appPath: 'app/dashboard/(main)/customize/page.tsx',
    component: Template_9,
    template:     {
        "name": "dashboard/(main)/customize/page",
        "themeName": "barbercrm",
        "templateType": "page",
        "fileName": "page.tsx",
        "relativePath": "dashboard/(main)/customize/page.tsx",
        "appPath": "app/dashboard/(main)/customize/page.tsx",
        "templatePath": "@/contents/themes/barbercrm/templates/dashboard/(main)/customize/page.tsx",
        "priority": 111,
        "metadata": null
    },
    alternatives:     []
  },
  'app/dashboard/(main)/products/page.tsx': {
    appPath: 'app/dashboard/(main)/products/page.tsx',
    component: Template_10,
    template:     {
        "name": "dashboard/(main)/products/page",
        "themeName": "barbercrm",
        "templateType": "page",
        "fileName": "page.tsx",
        "relativePath": "dashboard/(main)/products/page.tsx",
        "appPath": "app/dashboard/(main)/products/page.tsx",
        "templatePath": "@/contents/themes/barbercrm/templates/dashboard/(main)/products/page.tsx",
        "priority": 111,
        "metadata": null
    },
    alternatives:     []
  },
  'app/dashboard/analytics/loading.tsx': {
    appPath: 'app/dashboard/analytics/loading.tsx',
    component: Template_11,
    template:     {
        "name": "dashboard/analytics/loading",
        "themeName": "barbercrm",
        "templateType": "loading",
        "fileName": "loading.tsx",
        "relativePath": "dashboard/analytics/loading.tsx",
        "appPath": "app/dashboard/analytics/loading.tsx",
        "templatePath": "@/contents/themes/barbercrm/templates/dashboard/analytics/loading.tsx",
        "priority": 104,
        "metadata": null
    },
    alternatives:     []
  },
  'app/dashboard/analytics/page.tsx': {
    appPath: 'app/dashboard/analytics/page.tsx',
    component: Template_12,
    template:     {
        "name": "dashboard/analytics/page",
        "themeName": "barbercrm",
        "templateType": "page",
        "fileName": "page.tsx",
        "relativePath": "dashboard/analytics/page.tsx",
        "appPath": "app/dashboard/analytics/page.tsx",
        "templatePath": "@/contents/themes/barbercrm/templates/dashboard/analytics/page.tsx",
        "priority": 109,
        "metadata": null
    },
    alternatives:     []
  },
  'app/dashboard/settings/shop/page.tsx': {
    appPath: 'app/dashboard/settings/shop/page.tsx',
    component: Template_13,
    template:     {
        "name": "dashboard/settings/shop/page",
        "themeName": "barbercrm",
        "templateType": "page",
        "fileName": "page.tsx",
        "relativePath": "dashboard/settings/shop/page.tsx",
        "appPath": "app/dashboard/settings/shop/page.tsx",
        "templatePath": "@/contents/themes/barbercrm/templates/dashboard/settings/shop/page.tsx",
        "priority": 111,
        "metadata": null
    },
    alternatives:     []
  }
}

export type TemplatePath = keyof typeof TEMPLATE_REGISTRY extends never ? string : keyof typeof TEMPLATE_REGISTRY

/**
 * Template registry metadata
 */
export const TEMPLATE_METADATA = {
  totalTemplates: 14,
  uniquePaths: 14,
  templateTypes: ["layout","loading","page"],
  themeDistribution: {"barbercrm":14},
  generatedAt: '2026-05-31T16:00:45.253Z',
  paths: ['app/(public)/layout.tsx', 'app/(public)/loading.tsx', 'app/(public)/page.tsx', 'app/(public)/support/page.tsx', 'app/dashboard/(main)/appointments/page.tsx', 'app/dashboard/(main)/barbers/[id]/page.tsx', 'app/dashboard/(main)/calendar/page.tsx', 'app/dashboard/(main)/clients/[id]/page.tsx', 'app/dashboard/(main)/clients-alert/page.tsx', 'app/dashboard/(main)/customize/page.tsx', 'app/dashboard/(main)/products/page.tsx', 'app/dashboard/analytics/loading.tsx', 'app/dashboard/analytics/page.tsx', 'app/dashboard/settings/shop/page.tsx']
}
