/**
 * Auto-generated Feature Registry
 *
 * Generated at: 2026-05-31T11:38:05.511Z
 * Theme: barbercrm
 * Features: 12
 * Flows: 0
 *
 * DO NOT EDIT - This file is auto-generated by scripts/build-registry.mjs
 */

// =============================================================================
// TYPES
// =============================================================================

export interface FeatureTesting {
  hasTests: boolean
  testCount: number
  files: string[]
}

export interface FeatureEntry {
  key: string
  name: string
  description: string
  category: 'core' | 'entities' | 'content' | 'settings' | 'admin' | 'public'
  icon: string
  tag: string
  testing: FeatureTesting
}

export interface FlowEntry {
  key: string
  name: string
  description: string
  category: 'acquisition' | 'navigation' | 'content' | 'settings' | 'admin' | 'public'
  icon: string
  tag: string
  criticalPath?: boolean
  testing: FeatureTesting
}

export interface TagEntry {
  tag: string
  testCount: number
  files: string[]
}

// =============================================================================
// FEATURES REGISTRY
// =============================================================================

export const FEATURE_REGISTRY: Record<string, FeatureEntry> = {
  tasks: {
    key: "tasks",
    name: "Tasks",
    description: "Task tracking and assignment",
    category: "entities",
    icon: "check-square",
    tag: "feat-tasks",
    testing: {
      hasTests: false,
      testCount: 0,
      files: []
    }
  },
  booking: {
    key: "booking",
    name: "Online Booking",
    description: "Public booking wizard, barber schedules, and shop settings",
    category: "entities",
    icon: "calendar-check",
    tag: "feat-booking",
    testing: {
      hasTests: true,
      testCount: 4,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\uat\\booking\\booking-wizard.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\uat\\booking\\dashboard-calendar.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\uat\\booking\\dashboard-settings.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\uat\\booking\\security.cy.ts"
      ]
    }
  },
  "page-builder": {
    key: "page-builder",
    name: "Page Builder",
    description: "Visual block editor for page content",
    category: "content",
    icon: "layout",
    tag: "feat-page-builder",
    testing: {
      hasTests: false,
      testCount: 0,
      files: []
    }
  },
  patterns: {
    key: "patterns",
    name: "Patterns",
    description: "Reusable block patterns for page builder",
    category: "content",
    icon: "grid",
    tag: "feat-patterns",
    testing: {
      hasTests: true,
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    }
  },
  auth: {
    key: "auth",
    name: "Authentication",
    description: "User authentication, sessions, and account security",
    category: "core",
    icon: "shield",
    tag: "feat-auth",
    testing: {
      hasTests: false,
      testCount: 0,
      files: []
    }
  },
  teams: {
    key: "teams",
    name: "Teams",
    description: "Multi-tenant team management and membership",
    category: "core",
    icon: "users",
    tag: "feat-teams",
    testing: {
      hasTests: false,
      testCount: 0,
      files: []
    }
  },
  plans: {
    key: "plans",
    name: "Plans",
    description: "Plan catalog, comparison, and selection",
    category: "settings",
    icon: "credit-card",
    tag: "feat-plans",
    testing: {
      hasTests: false,
      testCount: 0,
      files: []
    }
  },
  billing: {
    key: "billing",
    name: "Billing",
    description: "Subscription management, payments, and invoices",
    category: "settings",
    icon: "receipt",
    tag: "feat-billing",
    testing: {
      hasTests: false,
      testCount: 0,
      files: []
    }
  },
  users: {
    key: "users",
    name: "User Profile",
    description: "User profile management and preferences",
    category: "settings",
    icon: "user",
    tag: "feat-users",
    testing: {
      hasTests: false,
      testCount: 0,
      files: []
    }
  },
  "api-keys": {
    key: "api-keys",
    name: "API Keys",
    description: "API key generation and management for integrations",
    category: "settings",
    icon: "key",
    tag: "feat-api-keys",
    testing: {
      hasTests: false,
      testCount: 0,
      files: []
    }
  },
  superadmin: {
    key: "superadmin",
    name: "Superadmin",
    description: "Superadmin dashboard and system management",
    category: "admin",
    icon: "shield-check",
    tag: "feat-superadmin",
    testing: {
      hasTests: false,
      testCount: 0,
      files: []
    }
  },
  devtools: {
    key: "devtools",
    name: "Developer Tools",
    description: "Development tools, test viewers, and configuration inspectors",
    category: "admin",
    icon: "terminal",
    tag: "feat-devtools",
    testing: {
      hasTests: false,
      testCount: 0,
      files: []
    }
  }
}

// =============================================================================
// FLOWS REGISTRY
// =============================================================================

export const FLOW_REGISTRY: Record<string, FlowEntry> = {}

// =============================================================================
// TAGS REGISTRY (all discovered tags)
// =============================================================================

export const TAGS_REGISTRY = {
  features: {
    booking: {
      tag: "@feat-booking",
      testCount: 4,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\uat\\booking\\booking-wizard.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\uat\\booking\\dashboard-calendar.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\uat\\booking\\dashboard-settings.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\uat\\booking\\security.cy.ts"
      ]
    },
    patterns: {
      tag: "@feat-patterns",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    }
  },
  flows: {},
  blocks: {},
  layers: {
    uat: {
      tag: "@uat",
      testCount: 12,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\uat\\booking\\booking-wizard.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\uat\\booking\\dashboard-calendar.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\uat\\booking\\dashboard-settings.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\uat\\booking\\security.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\uat\\entities\\tasks\\tasks-crud.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\devtools\\access.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\devtools\\navigation.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\devtools\\pages.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\superadmin\\all-teams.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\superadmin\\all-users.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\superadmin\\dashboard.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\superadmin\\subscriptions-overview.cy.ts"
      ]
    }
  },
  priorities: {
    smoke: {
      tag: "@smoke",
      testCount: 6,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\uat\\booking\\booking-wizard.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\devtools\\access.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\superadmin\\all-teams.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\superadmin\\all-users.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\superadmin\\dashboard.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\superadmin\\subscriptions-overview.cy.ts"
      ]
    },
    regression: {
      tag: "@regression",
      testCount: 7,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\uat\\booking\\booking-wizard.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\uat\\booking\\dashboard-calendar.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\uat\\booking\\dashboard-settings.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\uat\\booking\\security.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\devtools\\access.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\devtools\\navigation.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\devtools\\pages.cy.ts"
      ]
    }
  },
  roles: {
    owner: {
      tag: "@role-owner",
      testCount: 2,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\uat\\booking\\dashboard-calendar.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\uat\\booking\\dashboard-settings.cy.ts"
      ]
    }
  },
  operations: {
    security: {
      tag: "@security",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\uat\\booking\\security.cy.ts"
      ]
    },
    crud: {
      tag: "@crud",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\uat\\entities\\tasks\\tasks-crud.cy.ts"
      ]
    },
    search: {
      tag: "@search",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\global-search.cy.ts"
      ]
    }
  },
  other: {
    tasks: {
      tag: "@tasks",
      testCount: 2,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\uat\\entities\\tasks\\tasks-crud.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\tasks.cy.ts"
      ]
    },
    TASKS_CRUD_001: {
      tag: "@TASKS_CRUD_001",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\uat\\entities\\tasks\\tasks-crud.cy.ts"
      ]
    },
    TASKS_CRUD_002: {
      tag: "@TASKS_CRUD_002",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\uat\\entities\\tasks\\tasks-crud.cy.ts"
      ]
    },
    TASKS_CRUD_003: {
      tag: "@TASKS_CRUD_003",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\uat\\entities\\tasks\\tasks-crud.cy.ts"
      ]
    },
    TASKS_CRUD_004: {
      tag: "@TASKS_CRUD_004",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\uat\\entities\\tasks\\tasks-crud.cy.ts"
      ]
    },
    TASKS_CRUD_005: {
      tag: "@TASKS_CRUD_005",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\uat\\entities\\tasks\\tasks-crud.cy.ts"
      ]
    },
    TASKS_CRUD_006: {
      tag: "@TASKS_CRUD_006",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\uat\\entities\\tasks\\tasks-crud.cy.ts"
      ]
    },
    "area-devtools": {
      tag: "@area-devtools",
      testCount: 3,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\devtools\\access.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\devtools\\navigation.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\devtools\\pages.cy.ts"
      ]
    },
    "ui-selectors": {
      tag: "@ui-selectors",
      testCount: 20,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\auth.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\billing.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-container.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-mobile.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-navigation.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-sidebar.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-topnav.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\devtools.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\global-search.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\settings-api-keys.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\settings-billing.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\settings-layout.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\settings-password.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\settings-profile.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\settings-teams.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\superadmin.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\tasks.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\teams.cy.ts"
      ]
    },
    auth: {
      tag: "@auth",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\auth.cy.ts"
      ]
    },
    SEL_AUTH_001: {
      tag: "@SEL_AUTH_001",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\auth.cy.ts"
      ]
    },
    SEL_AUTH_002: {
      tag: "@SEL_AUTH_002",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\auth.cy.ts"
      ]
    },
    SEL_AUTH_003: {
      tag: "@SEL_AUTH_003",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\auth.cy.ts"
      ]
    },
    SEL_AUTH_004: {
      tag: "@SEL_AUTH_004",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\auth.cy.ts"
      ]
    },
    SEL_AUTH_005: {
      tag: "@SEL_AUTH_005",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\auth.cy.ts"
      ]
    },
    SEL_AUTH_006: {
      tag: "@SEL_AUTH_006",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\auth.cy.ts"
      ]
    },
    SEL_AUTH_007: {
      tag: "@SEL_AUTH_007",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\auth.cy.ts"
      ]
    },
    billing: {
      tag: "@billing",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\billing.cy.ts"
      ]
    },
    SEL_BILL_001: {
      tag: "@SEL_BILL_001",
      testCount: 2,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\billing.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\settings-billing.cy.ts"
      ]
    },
    SEL_BILL_002: {
      tag: "@SEL_BILL_002",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\billing.cy.ts"
      ]
    },
    SEL_BILL_003: {
      tag: "@SEL_BILL_003",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\billing.cy.ts"
      ]
    },
    SEL_BILL_004: {
      tag: "@SEL_BILL_004",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\billing.cy.ts"
      ]
    },
    SEL_BILL_005: {
      tag: "@SEL_BILL_005",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\billing.cy.ts"
      ]
    },
    SEL_BILL_006: {
      tag: "@SEL_BILL_006",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\billing.cy.ts"
      ]
    },
    SEL_BILL_DOC: {
      tag: "@SEL_BILL_DOC",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\billing.cy.ts"
      ]
    },
    "block-editor": {
      tag: "@block-editor",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    "selector-validation": {
      tag: "@selector-validation",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_001: {
      tag: "@SEL_BE_001",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_001_01: {
      tag: "@SEL_BE_001_01",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_001_02: {
      tag: "@SEL_BE_001_02",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_001_03: {
      tag: "@SEL_BE_001_03",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_001_04: {
      tag: "@SEL_BE_001_04",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_001_05: {
      tag: "@SEL_BE_001_05",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_001_06: {
      tag: "@SEL_BE_001_06",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_001_07: {
      tag: "@SEL_BE_001_07",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_001_08: {
      tag: "@SEL_BE_001_08",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_001_09: {
      tag: "@SEL_BE_001_09",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_001_10: {
      tag: "@SEL_BE_001_10",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_001_11: {
      tag: "@SEL_BE_001_11",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_002: {
      tag: "@SEL_BE_002",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_002_01: {
      tag: "@SEL_BE_002_01",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_002_02: {
      tag: "@SEL_BE_002_02",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_002_03: {
      tag: "@SEL_BE_002_03",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_002_04: {
      tag: "@SEL_BE_002_04",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_002_05: {
      tag: "@SEL_BE_002_05",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_002_06: {
      tag: "@SEL_BE_002_06",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_002_07: {
      tag: "@SEL_BE_002_07",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_002_08: {
      tag: "@SEL_BE_002_08",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_003: {
      tag: "@SEL_BE_003",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_003_01: {
      tag: "@SEL_BE_003_01",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_003_02: {
      tag: "@SEL_BE_003_02",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_003_03: {
      tag: "@SEL_BE_003_03",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_004: {
      tag: "@SEL_BE_004",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_004_01: {
      tag: "@SEL_BE_004_01",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_004_02: {
      tag: "@SEL_BE_004_02",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_004_03: {
      tag: "@SEL_BE_004_03",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_004_04: {
      tag: "@SEL_BE_004_04",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_004_05: {
      tag: "@SEL_BE_004_05",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_004_06: {
      tag: "@SEL_BE_004_06",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_004_07: {
      tag: "@SEL_BE_004_07",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_004_08: {
      tag: "@SEL_BE_004_08",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_005: {
      tag: "@SEL_BE_005",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_005_01: {
      tag: "@SEL_BE_005_01",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_005_02: {
      tag: "@SEL_BE_005_02",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_005_03: {
      tag: "@SEL_BE_005_03",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_005_04: {
      tag: "@SEL_BE_005_04",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_005_05: {
      tag: "@SEL_BE_005_05",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_005_06: {
      tag: "@SEL_BE_005_06",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_005_07: {
      tag: "@SEL_BE_005_07",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_006: {
      tag: "@SEL_BE_006",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_006_01: {
      tag: "@SEL_BE_006_01",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_006_02: {
      tag: "@SEL_BE_006_02",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_006_03: {
      tag: "@SEL_BE_006_03",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_006_04: {
      tag: "@SEL_BE_006_04",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_006_05: {
      tag: "@SEL_BE_006_05",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_006_06: {
      tag: "@SEL_BE_006_06",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_006_07: {
      tag: "@SEL_BE_006_07",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_006_08: {
      tag: "@SEL_BE_006_08",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_006_09: {
      tag: "@SEL_BE_006_09",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_007: {
      tag: "@SEL_BE_007",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_007_01: {
      tag: "@SEL_BE_007_01",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_007_02: {
      tag: "@SEL_BE_007_02",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_007_03: {
      tag: "@SEL_BE_007_03",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_007_04: {
      tag: "@SEL_BE_007_04",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_007_05: {
      tag: "@SEL_BE_007_05",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    SEL_BE_007_06: {
      tag: "@SEL_BE_007_06",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\block-editor.cy.ts"
      ]
    },
    dashboard: {
      tag: "@dashboard",
      testCount: 6,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-container.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-mobile.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-navigation.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-sidebar.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-topnav.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\superadmin\\dashboard.cy.ts"
      ]
    },
    container: {
      tag: "@container",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-container.cy.ts"
      ]
    },
    SEL_DCNT_001: {
      tag: "@SEL_DCNT_001",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-container.cy.ts"
      ]
    },
    mobile: {
      tag: "@mobile",
      testCount: 2,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-mobile.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\teams.cy.ts"
      ]
    },
    SEL_DMOB_DOC: {
      tag: "@SEL_DMOB_DOC",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-mobile.cy.ts"
      ]
    },
    SEL_DMOB_001: {
      tag: "@SEL_DMOB_001",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-mobile.cy.ts"
      ]
    },
    SEL_DMOB_002: {
      tag: "@SEL_DMOB_002",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-mobile.cy.ts"
      ]
    },
    SEL_DMOB_003: {
      tag: "@SEL_DMOB_003",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-mobile.cy.ts"
      ]
    },
    SEL_DMOB_004: {
      tag: "@SEL_DMOB_004",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-mobile.cy.ts"
      ]
    },
    SEL_DASH_001: {
      tag: "@SEL_DASH_001",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-navigation.cy.ts"
      ]
    },
    SEL_DASH_002: {
      tag: "@SEL_DASH_002",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-navigation.cy.ts"
      ]
    },
    SEL_DASH_003: {
      tag: "@SEL_DASH_003",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-navigation.cy.ts"
      ]
    },
    sidebar: {
      tag: "@sidebar",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-sidebar.cy.ts"
      ]
    },
    SEL_DBAR_001: {
      tag: "@SEL_DBAR_001",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-sidebar.cy.ts"
      ]
    },
    topnav: {
      tag: "@topnav",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-topnav.cy.ts"
      ]
    },
    SEL_TNAV_001: {
      tag: "@SEL_TNAV_001",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-topnav.cy.ts"
      ]
    },
    SEL_TNAV_002: {
      tag: "@SEL_TNAV_002",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-topnav.cy.ts"
      ]
    },
    SEL_TNAV_003: {
      tag: "@SEL_TNAV_003",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-topnav.cy.ts"
      ]
    },
    SEL_TNAV_004: {
      tag: "@SEL_TNAV_004",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-topnav.cy.ts"
      ]
    },
    SEL_TNAV_005: {
      tag: "@SEL_TNAV_005",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-topnav.cy.ts"
      ]
    },
    SEL_TNAV_006: {
      tag: "@SEL_TNAV_006",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-topnav.cy.ts"
      ]
    },
    SEL_TNAV_006_01: {
      tag: "@SEL_TNAV_006_01",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-topnav.cy.ts"
      ]
    },
    SEL_TNAV_007: {
      tag: "@SEL_TNAV_007",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-topnav.cy.ts"
      ]
    },
    SEL_TNAV_007_01: {
      tag: "@SEL_TNAV_007_01",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-topnav.cy.ts"
      ]
    },
    SEL_TNAV_007_02: {
      tag: "@SEL_TNAV_007_02",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-topnav.cy.ts"
      ]
    },
    SEL_TNAV_007_03: {
      tag: "@SEL_TNAV_007_03",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\dashboard-topnav.cy.ts"
      ]
    },
    devtools: {
      tag: "@devtools",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\devtools.cy.ts"
      ]
    },
    SEL_DEVT_001: {
      tag: "@SEL_DEVT_001",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\devtools.cy.ts"
      ]
    },
    SEL_DEVT_002: {
      tag: "@SEL_DEVT_002",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\devtools.cy.ts"
      ]
    },
    SEL_DEVT_003: {
      tag: "@SEL_DEVT_003",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\devtools.cy.ts"
      ]
    },
    SEL_DEVT_004: {
      tag: "@SEL_DEVT_004",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\devtools.cy.ts"
      ]
    },
    SEL_DEVT_005: {
      tag: "@SEL_DEVT_005",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\devtools.cy.ts"
      ]
    },
    SEL_DEVT_006: {
      tag: "@SEL_DEVT_006",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\devtools.cy.ts"
      ]
    },
    SEL_GSRCH_001: {
      tag: "@SEL_GSRCH_001",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\global-search.cy.ts"
      ]
    },
    SEL_GSRCH_002: {
      tag: "@SEL_GSRCH_002",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\global-search.cy.ts"
      ]
    },
    SEL_GSRCH_003: {
      tag: "@SEL_GSRCH_003",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\global-search.cy.ts"
      ]
    },
    patterns: {
      tag: "@patterns",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_001: {
      tag: "@SEL_PAT_001",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_001_01: {
      tag: "@SEL_PAT_001_01",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_001_02: {
      tag: "@SEL_PAT_001_02",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_001_03: {
      tag: "@SEL_PAT_001_03",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_001_04: {
      tag: "@SEL_PAT_001_04",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_001_05: {
      tag: "@SEL_PAT_001_05",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_002: {
      tag: "@SEL_PAT_002",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_002_01: {
      tag: "@SEL_PAT_002_01",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_002_02: {
      tag: "@SEL_PAT_002_02",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_002_03: {
      tag: "@SEL_PAT_002_03",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_002_04: {
      tag: "@SEL_PAT_002_04",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_003: {
      tag: "@SEL_PAT_003",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_003_01: {
      tag: "@SEL_PAT_003_01",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_003_02: {
      tag: "@SEL_PAT_003_02",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_003_03: {
      tag: "@SEL_PAT_003_03",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_003_04: {
      tag: "@SEL_PAT_003_04",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_003_05: {
      tag: "@SEL_PAT_003_05",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_004: {
      tag: "@SEL_PAT_004",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_004_01: {
      tag: "@SEL_PAT_004_01",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_004_02: {
      tag: "@SEL_PAT_004_02",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_004_03: {
      tag: "@SEL_PAT_004_03",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_004_04: {
      tag: "@SEL_PAT_004_04",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_004_05: {
      tag: "@SEL_PAT_004_05",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_005: {
      tag: "@SEL_PAT_005",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_005_01: {
      tag: "@SEL_PAT_005_01",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_005_02: {
      tag: "@SEL_PAT_005_02",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_005_03: {
      tag: "@SEL_PAT_005_03",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_005_04: {
      tag: "@SEL_PAT_005_04",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_006: {
      tag: "@SEL_PAT_006",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_006_01: {
      tag: "@SEL_PAT_006_01",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_006_02: {
      tag: "@SEL_PAT_006_02",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_006_03: {
      tag: "@SEL_PAT_006_03",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_007: {
      tag: "@SEL_PAT_007",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_007_01: {
      tag: "@SEL_PAT_007_01",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_007_02: {
      tag: "@SEL_PAT_007_02",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_007_03: {
      tag: "@SEL_PAT_007_03",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_007_04: {
      tag: "@SEL_PAT_007_04",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_007_05: {
      tag: "@SEL_PAT_007_05",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_007_06: {
      tag: "@SEL_PAT_007_06",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_008: {
      tag: "@SEL_PAT_008",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_008_01: {
      tag: "@SEL_PAT_008_01",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_008_02: {
      tag: "@SEL_PAT_008_02",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    SEL_PAT_008_03: {
      tag: "@SEL_PAT_008_03",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\patterns.cy.ts"
      ]
    },
    settings: {
      tag: "@settings",
      testCount: 6,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\settings-api-keys.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\settings-billing.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\settings-layout.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\settings-password.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\settings-profile.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\settings-teams.cy.ts"
      ]
    },
    SEL_API_001: {
      tag: "@SEL_API_001",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\settings-api-keys.cy.ts"
      ]
    },
    SEL_API_002: {
      tag: "@SEL_API_002",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\settings-api-keys.cy.ts"
      ]
    },
    SEL_API_003: {
      tag: "@SEL_API_003",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\settings-api-keys.cy.ts"
      ]
    },
    SEL_API_004: {
      tag: "@SEL_API_004",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\settings-api-keys.cy.ts"
      ]
    },
    SEL_API_005: {
      tag: "@SEL_API_005",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\settings-api-keys.cy.ts"
      ]
    },
    SEL_API_006: {
      tag: "@SEL_API_006",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\settings-api-keys.cy.ts"
      ]
    },
    SEL_LAY_001: {
      tag: "@SEL_LAY_001",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\settings-layout.cy.ts"
      ]
    },
    SEL_LAY_002: {
      tag: "@SEL_LAY_002",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\settings-layout.cy.ts"
      ]
    },
    SEL_PASS_001: {
      tag: "@SEL_PASS_001",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\settings-password.cy.ts"
      ]
    },
    SEL_PROF_001: {
      tag: "@SEL_PROF_001",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\settings-profile.cy.ts"
      ]
    },
    SEL_STMS_001: {
      tag: "@SEL_STMS_001",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\settings-teams.cy.ts"
      ]
    },
    SEL_STMS_002: {
      tag: "@SEL_STMS_002",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\settings-teams.cy.ts"
      ]
    },
    superadmin: {
      tag: "@superadmin",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\superadmin.cy.ts"
      ]
    },
    SEL_SADM_001: {
      tag: "@SEL_SADM_001",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\superadmin.cy.ts"
      ]
    },
    SEL_SADM_002: {
      tag: "@SEL_SADM_002",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\superadmin.cy.ts"
      ]
    },
    SEL_SADM_003: {
      tag: "@SEL_SADM_003",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\superadmin.cy.ts"
      ]
    },
    SEL_SADM_004: {
      tag: "@SEL_SADM_004",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\superadmin.cy.ts"
      ]
    },
    SEL_SADM_005: {
      tag: "@SEL_SADM_005",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\superadmin.cy.ts"
      ]
    },
    SEL_SADM_006: {
      tag: "@SEL_SADM_006",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\superadmin.cy.ts"
      ]
    },
    entities: {
      tag: "@entities",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\tasks.cy.ts"
      ]
    },
    SEL_TASK_PAGE_001: {
      tag: "@SEL_TASK_PAGE_001",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\tasks.cy.ts"
      ]
    },
    "entities-list": {
      tag: "@entities-list",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\tasks.cy.ts"
      ]
    },
    SEL_TASK_LIST_001: {
      tag: "@SEL_TASK_LIST_001",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\tasks.cy.ts"
      ]
    },
    SEL_TASK_LIST_002: {
      tag: "@SEL_TASK_LIST_002",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\tasks.cy.ts"
      ]
    },
    SEL_TASK_LIST_003: {
      tag: "@SEL_TASK_LIST_003",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\tasks.cy.ts"
      ]
    },
    SEL_TASK_LIST_004: {
      tag: "@SEL_TASK_LIST_004",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\tasks.cy.ts"
      ]
    },
    SEL_TASK_LIST_005: {
      tag: "@SEL_TASK_LIST_005",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\tasks.cy.ts"
      ]
    },
    SEL_TASK_LIST_006: {
      tag: "@SEL_TASK_LIST_006",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\tasks.cy.ts"
      ]
    },
    SEL_TASK_LIST_007: {
      tag: "@SEL_TASK_LIST_007",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\tasks.cy.ts"
      ]
    },
    SEL_TASK_HEADER_001: {
      tag: "@SEL_TASK_HEADER_001",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\tasks.cy.ts"
      ]
    },
    SEL_TASK_DETAIL_001: {
      tag: "@SEL_TASK_DETAIL_001",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\tasks.cy.ts"
      ]
    },
    SEL_TASK_FORM_001: {
      tag: "@SEL_TASK_FORM_001",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\tasks.cy.ts"
      ]
    },
    SEL_TASK_CHILD_001: {
      tag: "@SEL_TASK_CHILD_001",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\tasks.cy.ts"
      ]
    },
    teams: {
      tag: "@teams",
      testCount: 2,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\teams.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\superadmin\\all-teams.cy.ts"
      ]
    },
    "multi-team": {
      tag: "@multi-team",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\teams.cy.ts"
      ]
    },
    SEL_TEAM_001: {
      tag: "@SEL_TEAM_001",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\teams.cy.ts"
      ]
    },
    SEL_TEAM_003: {
      tag: "@SEL_TEAM_003",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\teams.cy.ts"
      ]
    },
    SEL_TEAM_004: {
      tag: "@SEL_TEAM_004",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\teams.cy.ts"
      ]
    },
    SEL_TEAM_006: {
      tag: "@SEL_TEAM_006",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\teams.cy.ts"
      ]
    },
    SEL_TEAM_007: {
      tag: "@SEL_TEAM_007",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\teams.cy.ts"
      ]
    },
    SEL_TEAM_008: {
      tag: "@SEL_TEAM_008",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\selectors\\teams.cy.ts"
      ]
    },
    "area-superadmin": {
      tag: "@area-superadmin",
      testCount: 4,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\superadmin\\all-teams.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\superadmin\\all-users.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\superadmin\\dashboard.cy.ts",
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\superadmin\\subscriptions-overview.cy.ts"
      ]
    },
    users: {
      tag: "@users",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\superadmin\\all-users.cy.ts"
      ]
    },
    subscriptions: {
      tag: "@subscriptions",
      testCount: 1,
      files: [
        "contents\\themes\\barbercrm\\tests\\cypress\\e2e\\_utils\\superadmin\\subscriptions-overview.cy.ts"
      ]
    }
  },
} as const

// =============================================================================
// COVERAGE SUMMARY
// =============================================================================

export const COVERAGE_SUMMARY = {
  theme: 'barbercrm',
  generatedAt: '2026-05-31T11:38:05.512Z',
  features: {
    total: 12,
    withTests: 2,
    withoutTests: 10,
  },
  flows: {
    total: 0,
    withTests: 0,
    withoutTests: 0,
  },
  tags: {
    total: 220,
    testFiles: 32,
  }
} as const

// =============================================================================
// HELPER TYPES
// =============================================================================

export type FeatureKey = keyof typeof FEATURE_REGISTRY
export type FlowKey = keyof typeof FLOW_REGISTRY
export type FeatureCategory = FeatureEntry['category']
export type FlowCategory = FlowEntry['category']
