/**
 * Auto-generated Theme Registry
 *
 * Generated at: 2026-05-31T16:00:45.247Z
 * Themes discovered: 1
 *
 * DO NOT EDIT - This file is auto-generated by scripts/build-registry.mjs
 */

import { barbercrmThemeConfig } from '@/contents/themes/barbercrm/config/theme.config'
import { DASHBOARD_CONFIG as barbercrmDashboardConfig } from '@/contents/themes/barbercrm/config/dashboard.config'
import { APP_CONFIG_OVERRIDES as barbercrmAppConfig } from '@/contents/themes/barbercrm/config/app.config'
import { DEV_CONFIG_OVERRIDES as barbercrmDevConfig } from '@/contents/themes/barbercrm/config/dev.config'
import type { ThemeConfig } from '@nextsparkjs/core/types/theme'
import type { DevConfig } from '@nextsparkjs/core/lib/config/types'

export interface ThemeEntity {
  name: string
  exportName: string
  configPath: string
  actualConfigFile: string
  relativePath: string
  depth: number
  parent: string | null
  children: string[]
  hasComponents: boolean
  hasHooks: boolean
  hasMigrations: boolean
  hasMessages: boolean
  hasAssets: boolean
  messagesPath: string
  pluginContext: { pluginName: string } | null
  themeContext: { themeName: string } | null
  source: string
}

export interface ThemeRouteFile {
  path: string
  filePath: string
  relativePath: string
  methods: string[]
  isRouteFile: boolean
  theme: string
}

export interface ThemeRegistryEntry {
  name: string
  config: ThemeConfig
  hasComponents: boolean
  hasStyles: boolean
  hasAssets: boolean
  hasMessages: boolean
  hasDashboardConfig: boolean
  dashboardConfig: any | null
  hasAppConfig: boolean
  appConfig: any | null
  hasDevConfig: boolean
  devConfig: DevConfig | null
  hasScheduledActions: boolean
  scheduledActionsPath: string | null
  componentsPath: string | null
  stylesPath: string | null
  assetsPath: string | null
  messagesPath: string | null
  entities: ThemeEntity[]
  routeFiles: ThemeRouteFile[]
  plugins: string[]
}

export const THEME_REGISTRY: Record<string, ThemeRegistryEntry> = {
  'barbercrm': {
    name: 'barbercrm',
    config: barbercrmThemeConfig,
    hasComponents: true,
    hasStyles: true,
    hasAssets: false,
    hasMessages: true,
    hasDashboardConfig: true,
    dashboardConfig: barbercrmDashboardConfig,
    hasAppConfig: true,
    appConfig: barbercrmAppConfig,
    hasDevConfig: true,
    devConfig: barbercrmDevConfig,
    hasScheduledActions: false,
    scheduledActionsPath: null,
    componentsPath: '@/contents/themes/barbercrm/components',
    stylesPath: '@/contents/themes/barbercrm/styles',
    assetsPath: null,
    messagesPath: '@/contents/themes/barbercrm/messages',
    entities:     [
          {
                "name": "appointments",
                "exportName": "appointmentEntityConfig",
                "configPath": "@/contents/themes/barbercrm/entities/appointments/appointments.config",
                "actualConfigFile": "appointments.config.ts",
                "relativePath": "appointments",
                "depth": 0,
                "parent": null,
                "children": [],
                "hasComponents": false,
                "hasHooks": false,
                "hasMigrations": true,
                "hasMessages": true,
                "hasAssets": false,
                "messagesPath": "@/contents/themes/barbercrm/entities/appointments/messages",
                "pluginContext": null,
                "themeContext": {
                      "themeName": "barbercrm"
                },
                "source": "theme"
          },
          {
                "name": "barbers",
                "exportName": "barberEntityConfig",
                "configPath": "@/contents/themes/barbercrm/entities/barbers/barbers.config",
                "actualConfigFile": "barbers.config.ts",
                "relativePath": "barbers",
                "depth": 0,
                "parent": null,
                "children": [],
                "hasComponents": false,
                "hasHooks": false,
                "hasMigrations": true,
                "hasMessages": true,
                "hasAssets": false,
                "messagesPath": "@/contents/themes/barbercrm/entities/barbers/messages",
                "pluginContext": null,
                "themeContext": {
                      "themeName": "barbercrm"
                },
                "source": "theme"
          },
          {
                "name": "clients",
                "exportName": "clientEntityConfig",
                "configPath": "@/contents/themes/barbercrm/entities/clients/clients.config",
                "actualConfigFile": "clients.config.ts",
                "relativePath": "clients",
                "depth": 0,
                "parent": null,
                "children": [],
                "hasComponents": false,
                "hasHooks": false,
                "hasMigrations": true,
                "hasMessages": true,
                "hasAssets": false,
                "messagesPath": "@/contents/themes/barbercrm/entities/clients/messages",
                "pluginContext": null,
                "themeContext": {
                      "themeName": "barbercrm"
                },
                "source": "theme"
          },
          {
                "name": "pages",
                "exportName": "pagesEntityConfig",
                "configPath": "@/contents/themes/barbercrm/entities/pages/pages.config",
                "actualConfigFile": "pages.config.ts",
                "relativePath": "pages",
                "depth": 0,
                "parent": null,
                "children": [],
                "hasComponents": false,
                "hasHooks": false,
                "hasMigrations": true,
                "hasMessages": true,
                "hasAssets": false,
                "messagesPath": "@/contents/themes/barbercrm/entities/pages/messages",
                "pluginContext": null,
                "themeContext": {
                      "themeName": "barbercrm"
                },
                "source": "theme"
          },
          {
                "name": "posts",
                "exportName": "postsEntityConfig",
                "configPath": "@/contents/themes/barbercrm/entities/posts/posts.config",
                "actualConfigFile": "posts.config.ts",
                "relativePath": "posts",
                "depth": 0,
                "parent": null,
                "children": [],
                "hasComponents": true,
                "hasHooks": false,
                "hasMigrations": true,
                "hasMessages": true,
                "hasAssets": false,
                "messagesPath": "@/contents/themes/barbercrm/entities/posts/messages",
                "pluginContext": null,
                "themeContext": {
                      "themeName": "barbercrm"
                },
                "source": "theme"
          },
          {
                "name": "products",
                "exportName": "productEntityConfig",
                "configPath": "@/contents/themes/barbercrm/entities/products/products.config",
                "actualConfigFile": "products.config.ts",
                "relativePath": "products",
                "depth": 0,
                "parent": null,
                "children": [],
                "hasComponents": false,
                "hasHooks": false,
                "hasMigrations": true,
                "hasMessages": true,
                "hasAssets": false,
                "messagesPath": "@/contents/themes/barbercrm/entities/products/messages",
                "pluginContext": null,
                "themeContext": {
                      "themeName": "barbercrm"
                },
                "source": "theme"
          },
          {
                "name": "services",
                "exportName": "serviceEntityConfig",
                "configPath": "@/contents/themes/barbercrm/entities/services/services.config",
                "actualConfigFile": "services.config.ts",
                "relativePath": "services",
                "depth": 0,
                "parent": null,
                "children": [],
                "hasComponents": false,
                "hasHooks": false,
                "hasMigrations": true,
                "hasMessages": true,
                "hasAssets": false,
                "messagesPath": "@/contents/themes/barbercrm/entities/services/messages",
                "pluginContext": null,
                "themeContext": {
                      "themeName": "barbercrm"
                },
                "source": "theme"
          },
          {
                "name": "tasks",
                "exportName": "taskEntityConfig",
                "configPath": "@/contents/themes/barbercrm/entities/tasks/tasks.config",
                "actualConfigFile": "tasks.config.ts",
                "relativePath": "tasks",
                "depth": 0,
                "parent": null,
                "children": [],
                "hasComponents": false,
                "hasHooks": false,
                "hasMigrations": true,
                "hasMessages": true,
                "hasAssets": false,
                "messagesPath": "@/contents/themes/barbercrm/entities/tasks/messages",
                "pluginContext": null,
                "themeContext": {
                      "themeName": "barbercrm"
                },
                "source": "theme"
          }
    ],
    routeFiles:     [],
    plugins: []
  }
}

export type ThemeName = keyof typeof THEME_REGISTRY

/**
 * Theme registry metadata
 */
export const THEME_METADATA = {
  totalThemes: 1,
  themesWithComponents: 1,
  themesWithStyles: 1,
  themesWithAssets: 0,
  themesWithMessages: 1,
  themesWithDashboardConfig: 1,
  themesWithAppConfig: 1,
  themesWithDevConfig: 1,
  themesWithScheduledActions: 0,
  themesWithEntities: 1,
  themesWithRoutes: 0,
  themesUsingPlugins: 0,
  totalThemeEntities: 8,
  totalThemeRoutes: 0,
  generatedAt: '2026-05-31T16:00:45.247Z',
  themes: ['barbercrm']
}
