/**
 * Auto-generated Translation Registry
 *
 * Generated at: 2026-05-31T16:00:45.252Z
 * Active theme: barbercrm
 * Supported locales: en, es
 * Themes with translations: 1
 * Total theme translation files: 2
 * Total entity translation files: 16
 * Total entities with translations: 8
 * Total plugin entity translation files: 0
 * Total plugin entities with translations: 0
 *
 * DO NOT EDIT - This file is auto-generated by scripts/build-registry.mjs
 *
 * Locale discovery: Dynamically scans messages/ directories and filters by supportedLocales.
 * ZERO runtime string interpolation - all translation paths resolved at build time.
 * Preserves lazy-loading performance (only loads active locale).
 * Provides build-time validation and type safety.
 */

export type TranslationLoader = () => Promise<{ default: Record<string, unknown> } | Record<string, unknown>>

/**
 * Theme Translation Loaders Registry
 * Access: THEME_TRANSLATION_LOADERS['theme-name']['locale']()
 *
 * Returns lazy-loading functions that only execute when called.
 * This preserves i18n performance - only active locale is loaded.
 */
export const THEME_TRANSLATION_LOADERS: Record<string, Record<string, TranslationLoader>> = {
  'barbercrm': {
    'en': () => import('@/contents/themes/barbercrm/messages/en'),
    'es': () => import('@/contents/themes/barbercrm/messages/es')
  }
}

/**
 * Entity Translation Loaders Registry
 * Access: ENTITY_TRANSLATION_LOADERS['theme-name']['entity-name']['locale']()
 *
 * Returns lazy-loading functions for entity-specific translations.
 * Structure: theme -> entity -> locale -> loader
 */
export const ENTITY_TRANSLATION_LOADERS: Record<string, Record<string, Record<string, TranslationLoader>>> = {
  'barbercrm': {
    'appointments': {
      'en': () => import('@/contents/themes/barbercrm/entities/appointments/messages/en.json'),
      'es': () => import('@/contents/themes/barbercrm/entities/appointments/messages/es.json')
    },
    'barbers': {
      'en': () => import('@/contents/themes/barbercrm/entities/barbers/messages/en.json'),
      'es': () => import('@/contents/themes/barbercrm/entities/barbers/messages/es.json')
    },
    'clients': {
      'en': () => import('@/contents/themes/barbercrm/entities/clients/messages/en.json'),
      'es': () => import('@/contents/themes/barbercrm/entities/clients/messages/es.json')
    },
    'pages': {
      'en': () => import('@/contents/themes/barbercrm/entities/pages/messages/en.json'),
      'es': () => import('@/contents/themes/barbercrm/entities/pages/messages/es.json')
    },
    'posts': {
      'en': () => import('@/contents/themes/barbercrm/entities/posts/messages/en.json'),
      'es': () => import('@/contents/themes/barbercrm/entities/posts/messages/es.json')
    },
    'products': {
      'en': () => import('@/contents/themes/barbercrm/entities/products/messages/en.json'),
      'es': () => import('@/contents/themes/barbercrm/entities/products/messages/es.json')
    },
    'services': {
      'en': () => import('@/contents/themes/barbercrm/entities/services/messages/en.json'),
      'es': () => import('@/contents/themes/barbercrm/entities/services/messages/es.json')
    },
    'tasks': {
      'en': () => import('@/contents/themes/barbercrm/entities/tasks/messages/en.json'),
      'es': () => import('@/contents/themes/barbercrm/entities/tasks/messages/es.json')
    }
  }
}

/**
 * Plugin Entity Translation Loaders Registry
 * Access: PLUGIN_ENTITY_TRANSLATION_LOADERS['plugin-name']['entity-name']['locale']()
 *
 * Used as fallback when theme doesn't define translations for an entity.
 * Theme translations always take priority over plugin translations.
 * Structure: plugin -> entity -> locale -> loader
 */
export const PLUGIN_ENTITY_TRANSLATION_LOADERS: Record<string, Record<string, Record<string, TranslationLoader>>> = {
  // No plugin entity translations discovered
}

/**
 * Translation registry metadata
 */
export const TRANSLATION_METADATA = {
  totalThemes: 1,
  totalThemeTranslations: 2,
  totalEntityTranslations: 16,
  totalEntitiesWithTranslations: 8,
  generatedAt: '2026-05-31T16:00:45.252Z',
  activeTheme: 'barbercrm',
  supportedLocales: ['en', 'es'],
  themes: ['barbercrm'],
  entities: ['barbercrm:appointments', 'barbercrm:barbers', 'barbercrm:clients', 'barbercrm:pages', 'barbercrm:posts', 'barbercrm:products', 'barbercrm:services', 'barbercrm:tasks'],
  totalPluginEntityTranslations: 0,
  totalPluginEntitiesWithTranslations: 0,
  pluginEntities: []
}

// PPR static exports disabled — cacheComponents: true not found in next.config.
// To enable PPR, add cacheComponents: true to your next.config and copy
// layout.ppr.tsx from @nextsparkjs/core/templates/app/ to your app/ directory.
// See docs/migration-ppr.md for the full migration guide.
