/**
 * Template page - directly imports from theme
 * Template: app/dashboard/(main)/clients/[id]/page.tsx
 * Generated by: scripts/build-registry.mjs
 */
import TemplateComponent from '@/contents/themes/barbercrm/templates/dashboard/(main)/clients/[id]/page'

// Direct export of the theme template (no fallback)
export default TemplateComponent
