import type { EntityField } from '@nextsparkjs/core/lib/entities/types'

export const productFields: EntityField[] = [
  {
    name: 'name',
    type: 'text',
    required: true,
    display: {
      label: 'Name',
      description: 'Product name',
      placeholder: 'Enter product name...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 1,
      columnWidth: 12,
    },
    api: {
      readOnly: false,
      searchable: true,
      sortable: true,
    },
  },
  {
    name: 'description',
    type: 'textarea',
    required: false,
    display: {
      label: 'Description',
      description: 'Product description',
      placeholder: 'Enter product description...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 2,
      columnWidth: 12,
    },
    api: {
      readOnly: false,
      searchable: true,
      sortable: false,
    },
  },
  {
    name: 'price',
    type: 'number',
    required: true,
    display: {
      label: 'Price',
      description: 'Product price',
      placeholder: '0.00',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 3,
      columnWidth: 4,
    },
    api: {
      readOnly: false,
      searchable: false,
      sortable: true,
    },
  },
  {
    name: 'stock',
    type: 'number',
    required: false,
    defaultValue: 0,
    display: {
      label: 'Stock',
      description: 'Units available in stock',
      placeholder: '0',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 4,
      columnWidth: 4,
    },
    api: {
      readOnly: false,
      searchable: false,
      sortable: true,
    },
  },
  {
    name: 'category',
    type: 'select',
    required: false,
    defaultValue: 'other',
    options: [
      { value: 'shampoo', label: 'Shampoo' },
      { value: 'conditioner', label: 'Conditioner' },
      { value: 'styling', label: 'Styling' },
      { value: 'tools', label: 'Tools' },
      { value: 'other', label: 'Other' },
    ],
    display: {
      label: 'Category',
      description: 'Product category',
      placeholder: 'Select category...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 5,
      columnWidth: 4,
    },
    api: {
      readOnly: false,
      searchable: false,
      sortable: true,
    },
  },
]
