import type { EntityField } from '@nextsparkjs/core/lib/entities/types'

export const barberFields: EntityField[] = [
  {
    name: 'name',
    type: 'text',
    required: true,
    display: {
      label: 'Full Name',
      description: 'Barber full name',
      placeholder: 'Enter barber name...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 1,
      columnWidth: 8,
    },
    api: { readOnly: false, searchable: true, sortable: true },
  },
  {
    name: 'specialty',
    type: 'text',
    required: false,
    display: {
      label: 'Specialty',
      description: 'Barber\'s main specialty',
      placeholder: 'e.g. Fades, Classic cuts',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 2,
      columnWidth: 4,
    },
    api: { readOnly: false, searchable: true, sortable: false },
  },
  {
    name: 'phone',
    type: 'text',
    required: false,
    display: {
      label: 'Phone',
      description: 'Barber phone number',
      placeholder: '+1 555 000 0000',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 3,
      columnWidth: 6,
    },
    api: { readOnly: false, searchable: false, sortable: false },
  },
  {
    name: 'email',
    type: 'text',
    required: false,
    display: {
      label: 'Email',
      description: 'Barber email address',
      placeholder: 'barber@email.com',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 4,
      columnWidth: 6,
    },
    api: { readOnly: false, searchable: false, sortable: false },
  },
  {
    name: 'active',
    type: 'boolean',
    required: false,
    defaultValue: true,
    display: {
      label: 'Active',
      description: 'Whether the barber is currently working',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 5,
      columnWidth: 4,
    },
    api: { readOnly: false, searchable: false, sortable: false },
  },
  {
    name: 'bio',
    type: 'textarea',
    required: false,
    display: {
      label: 'Bio',
      description: 'Barber biography',
      placeholder: 'Write a short bio...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 6,
      columnWidth: 12,
    },
    api: { readOnly: false, searchable: false, sortable: false },
  },
]
