/**
 * Template page - directly imports from theme
 * Template: app/(public)/loading.tsx
 * Generated by: scripts/build-registry.mjs
 */
import TemplateComponent from '@/contents/themes/barbercrm/templates/(public)/loading'

// Direct export of the theme template (no fallback)
export default TemplateComponent
