import type { EntityField } from '@nextsparkjs/core/lib/entities/types'

export const appointmentFields: EntityField[] = [
  {
    name: 'clientId',
    type: 'text',
    required: true,
    display: {
      label: 'Client ID',
      description: 'Client for this appointment',
      placeholder: 'Client ID...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 1,
      columnWidth: 6,
    },
    api: { readOnly: false, searchable: true, sortable: false },
  },
  {
    name: 'barberId',
    type: 'text',
    required: true,
    display: {
      label: 'Barber ID',
      description: 'Barber for this appointment',
      placeholder: 'Barber ID...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 2,
      columnWidth: 6,
    },
    api: { readOnly: false, searchable: true, sortable: false },
  },
  {
    name: 'serviceId',
    type: 'text',
    required: true,
    display: {
      label: 'Service ID',
      description: 'Service for this appointment',
      placeholder: 'Service ID...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 3,
      columnWidth: 6,
    },
    api: { readOnly: false, searchable: false, sortable: false },
  },
  {
    name: 'date',
    type: 'date',
    required: true,
    display: {
      label: 'Date',
      description: 'Appointment date',
      placeholder: 'Select date...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 4,
      columnWidth: 4,
    },
    api: { readOnly: false, searchable: false, sortable: true },
  },
  {
    name: 'time',
    type: 'text',
    required: true,
    display: {
      label: 'Time',
      description: 'Appointment time (HH:MM)',
      placeholder: '09:00',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 5,
      columnWidth: 4,
    },
    api: { readOnly: false, searchable: false, sortable: false },
  },
  {
    name: 'status',
    type: 'select',
    required: false,
    defaultValue: 'scheduled',
    options: [
      { value: 'scheduled', label: 'Scheduled' },
      { value: 'confirmed', label: 'Confirmed' },
      { value: 'in-progress', label: 'In Progress' },
      { value: 'completed', label: 'Completed' },
      { value: 'cancelled', label: 'Cancelled' },
      { value: 'no-show', label: 'No Show' },
    ],
    display: {
      label: 'Status',
      description: 'Appointment status',
      placeholder: 'Select status...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 6,
      columnWidth: 4,
    },
    api: { readOnly: false, searchable: false, sortable: true },
  },
  {
    name: 'totalPrice',
    type: 'number',
    required: false,
    display: {
      label: 'Total Price',
      description: 'Total price for this appointment',
      placeholder: '0.00',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 7,
      columnWidth: 4,
    },
    api: { readOnly: false, searchable: false, sortable: true },
  },
  {
    name: 'notes',
    type: 'textarea',
    required: false,
    display: {
      label: 'Notes',
      description: 'Appointment notes',
      placeholder: 'Add notes...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 8,
      columnWidth: 12,
    },
    api: { readOnly: false, searchable: false, sortable: false },
  },
]
